//! bionic's wide-character classification and case mapping: `iswalpha` and its family,
//! `towlower`, `towupper`.
//!
//! # What bionic does, and so what this does
//!
//! bionic's `libc/bionic/wctype.cpp` (`android-13.0.0_r1`) answers every one of these through
//! ICU -- `u_hasBinaryProperty` with `UCHAR_ALPHABETIC`, `UCHAR_LOWERCASE`, `UCHAR_UPPERCASE`,
//! `UCHAR_WHITE_SPACE`, `UCHAR_POSIX_BLANK`, `UCHAR_POSIX_GRAPH`, `UCHAR_POSIX_PRINT`,
//! `UCHAR_POSIX_XDIGIT`; `u_charType(c) == U_CONTROL_CHAR` for `iswcntrl`; `u_isdigit`;
//! `u_ispunct`; `u_tolower`/`u_toupper` above ASCII -- and the `_l` forms ignore the locale. ICU
//! is always present on a device, so its answer is the device's, and the C-locale fallbacks bionic
//! carries for a missing ICU are never taken.
//!
//! ICU's definitions of those predicates (`uchar.cpp`, ICU 71) are what this module implements,
//! over Unicode 14.0 data ([`crate::unicode14`], generated by `tools/gen_unicode14.py`) -- the
//! Unicode release ICU 71 carries, on the Android 13 this runtime reports:
//!
//! * `u_isdigit` is general category `Nd`; `u_ispunct` is `P*`; `iswcntrl` is `Cc`.
//! * `u_isblank`: TAB or SPACE at or below U+009F, `Zs` above.
//! * `u_isgraphPOSIX`: not `Cc`, `Cs`, `Cn` or `Z*`. `u_isprintPOSIX`: `Zs`, or graph.
//! * `u_isxdigit`: ASCII and fullwidth `A-F`/`a-f`, or `Nd`.
//! * `u_tolower`/`u_toupper`: the simple mappings of UnicodeData.txt; a character without one
//!   maps to itself -- `ß` has no simple uppercase, so `towupper('ß')` is `'ß'`.
//!
//! **Not** the C locale's ASCII tables, even for ASCII, because bionic does not use them either:
//! `iswpunct('$')` is **0** on Android 13 -- `$` is `Sc`, a currency symbol, not punctuation -- where
//! `ispunct('$')` is non-zero. A value outside Unicode (`WEOF` included) has no properties: every
//! predicate is 0 and both mappings return it unchanged, as ICU does for an invalid code point.

use crate::unicode14 as ucd;

fn in_ranges(table: &[(u32, u32)], c: u32) -> bool {
    table
        .binary_search_by(|&(low, high)| {
            if high < c {
                core::cmp::Ordering::Less
            } else if low > c {
                core::cmp::Ordering::Greater
            } else {
                core::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

fn mapped(table: &[(u32, u32)], c: u32) -> u32 {
    table.binary_search_by_key(&c, |&(from, _)| from).map_or(c, |at| table[at].1)
}

fn answer(yes: bool) -> i32 {
    i32::from(yes)
}

/// `iswalpha`: `UCHAR_ALPHABETIC`.
#[must_use]
pub fn iswalpha(c: u32) -> i32 {
    answer(in_ranges(ucd::ALPHABETIC, c))
}

/// `iswlower`: `UCHAR_LOWERCASE`.
#[must_use]
pub fn iswlower(c: u32) -> i32 {
    answer(in_ranges(ucd::LOWERCASE, c))
}

/// `iswupper`: `UCHAR_UPPERCASE`.
#[must_use]
pub fn iswupper(c: u32) -> i32 {
    answer(in_ranges(ucd::UPPERCASE, c))
}

/// `iswspace`: `UCHAR_WHITE_SPACE`.
#[must_use]
pub fn iswspace(c: u32) -> i32 {
    answer(in_ranges(ucd::WHITE_SPACE, c))
}

/// `iswblank`: ICU's `u_isblank` -- TAB or SPACE at or below U+009F, `Zs` above.
#[must_use]
pub fn iswblank(c: u32) -> i32 {
    answer(if c <= 0x9f { c == 0x09 || c == 0x20 } else { in_ranges(ucd::GC_ZS, c) })
}

/// `iswcntrl`: `u_charType(c) == U_CONTROL_CHAR`, general category `Cc`.
#[must_use]
pub fn iswcntrl(c: u32) -> i32 {
    answer(in_ranges(ucd::GC_CC, c))
}

/// `iswdigit`: `u_isdigit`, general category `Nd`.
#[must_use]
pub fn iswdigit(c: u32) -> i32 {
    answer(in_ranges(ucd::GC_ND, c))
}

/// `iswpunct`: `u_ispunct`, general categories `P*`.
#[must_use]
pub fn iswpunct(c: u32) -> i32 {
    answer(in_ranges(ucd::GC_P, c))
}

/// `iswgraph`: `u_isgraphPOSIX` -- a code point that is not `Cc`, `Cs`, `Cn` or `Z*`.
#[must_use]
pub fn iswgraph(c: u32) -> i32 {
    answer(c <= 0x10_ffff && !in_ranges(ucd::NOT_GRAPH, c))
}

/// `iswprint`: `u_isprintPOSIX` -- `Zs`, or graph.
#[must_use]
pub fn iswprint(c: u32) -> i32 {
    answer(in_ranges(ucd::GC_ZS, c) || iswgraph(c) != 0)
}

/// `iswxdigit`: `u_isxdigit` -- ASCII or fullwidth `A-F`/`a-f`, or `Nd`.
#[must_use]
pub fn iswxdigit(c: u32) -> i32 {
    let letter = (0x41..=0x46).contains(&c)
        || (0x61..=0x66).contains(&c)
        || (0xff21..=0xff26).contains(&c)
        || (0xff41..=0xff46).contains(&c);
    answer(letter || in_ranges(ucd::GC_ND, c))
}

/// `towlower`: ASCII by arithmetic, as bionic does, and `u_tolower`'s simple mapping above it.
#[must_use]
pub fn towlower(c: u32) -> u32 {
    if c < 0x80 {
        return if (0x41..=0x5a).contains(&c) { c | 0x20 } else { c };
    }
    mapped(ucd::TO_LOWER, c)
}

/// `towupper`: ASCII by arithmetic, as bionic does, and `u_toupper`'s simple mapping above it.
#[must_use]
pub fn towupper(c: u32) -> u32 {
    if c < 0x80 {
        return if (0x61..=0x7a).contains(&c) { c ^ 0x20 } else { c };
    }
    mapped(ucd::TO_UPPER, c)
}

#[cfg(test)]
mod tests {
    use super::*;

    const WEOF: u32 = 0xFFFF_FFFF;

    /// ICU's answers, not the C locale's: `$`, `+` and `^` are symbols, not punctuation.
    #[test]
    fn punctuation_is_unicodes_not_the_c_locales() {
        for c in ['!', '"', '#', '%', '&', '(', ',', '-', '.', '/', ':', '?', '@', '[', '_', '{'] {
            assert_eq!(iswpunct(c as u32), 1, "{c:?} is P*");
        }
        for c in ['$', '+', '<', '=', '>', '^', '`', '|', '~'] {
            assert_eq!(iswpunct(c as u32), 0, "{c:?} is S*, not punctuation");
        }
        assert_eq!(iswpunct(0x00BF), 1, "¿");
    }

    #[test]
    fn digits_blanks_and_controls_follow_icu() {
        assert_eq!(iswdigit('7' as u32), 1);
        assert_eq!(iswdigit(0x0660), 1, "ARABIC-INDIC DIGIT ZERO is Nd");
        assert_eq!(iswdigit(0x00B2), 0, "SUPERSCRIPT TWO is No");
        assert_eq!(iswxdigit(0xFF21), 1, "FULLWIDTH A");
        assert_eq!(iswxdigit('g' as u32), 0);
        assert_eq!(iswblank(0x0085), 0, "NEL is not blank at or below U+009F");
        assert_eq!(iswspace(0x0085), 1, "but it is White_Space");
        assert_eq!(iswblank(0x3000), 1, "IDEOGRAPHIC SPACE is Zs");
        assert_eq!(iswcntrl(0x0085), 1, "Cc");
        assert_eq!(iswprint(0x3000), 1, "Zs is printable");
        assert_eq!(iswgraph(0x3000), 0, "but not graph");
        assert_eq!(iswgraph(0xE000), 1, "private use is graph");
        assert_eq!(iswgraph(0xD800), 0, "a surrogate is not");
    }

    /// Unicode **14.0**, the release ICU 71 on Android 13 carries: U+1E030 (MODIFIER LETTER
    /// CYRILLIC SMALL A) was assigned in 15.0, so on the device it is unassigned -- neither a letter
    /// nor graph -- whatever a later table says.
    #[test]
    fn a_character_from_a_later_unicode_is_unassigned_here() {
        assert_eq!(iswalpha(0x1E030), 0);
        assert_eq!(iswgraph(0x1E030), 0);
        assert_eq!(iswalpha(0x1E7E0), 1, "ETHIOPIC SYLLABLE HHYA, new in 14.0");
    }

    #[test]
    fn simple_case_mappings() {
        assert_eq!(towupper('a' as u32), 'A' as u32);
        assert_eq!(towlower('Z' as u32), 'z' as u32);
        assert_eq!(towupper(0x00DF), 0x00DF, "ß has no simple uppercase");
        assert_eq!(towlower(0x1E9E), 0x00DF, "ẞ lowercases to ß");
        assert_eq!(towlower(0x0130), 'i' as u32, "İ's simple lowercase is i");
        assert_eq!(towupper(0x0101), 0x0100);
        assert_eq!(towupper(0x4E00), 0x4E00, "no case");
    }

    #[test]
    fn weof_and_values_outside_unicode_have_no_properties() {
        for c in [WEOF, 0x11_0000] {
            for f in [iswalpha, iswlower, iswupper, iswspace, iswblank, iswcntrl, iswdigit] {
                assert_eq!(f(c), 0, "{c:#x}");
            }
            for f in [iswpunct, iswgraph, iswprint, iswxdigit] {
                assert_eq!(f(c), 0, "{c:#x}");
            }
            assert_eq!(towlower(c), c);
            assert_eq!(towupper(c), c);
        }
    }
}
