// generated by tools/gen_aidl.py -- do not edit
//! `android.hardware.graphics.common` V5, from the frozen AIDL API in `tools/aidl/android.hardware.graphics.common/5/` (interface hash `2ffe8da1136972e9b6bed7903f0d5aca289005a9`).
#![allow(
    non_camel_case_types,
    non_upper_case_globals,
    dead_code,
    unused_imports,
    unused_variables,
    unused_parens,
    clippy::all,
    clippy::pedantic
)]

use std::sync::Arc;

use crate::binder::{Broker, HostCall, HostReply};
use crate::hal::aidl::runtime::*;
use crate::hal::parcel::{Malformed, Reader, Writer};
use crate::hal::aidl::{android_hardware_common, android_hardware_graphics_composer3};

/// `android.hardware.graphics.common.AlphaInterpretation`: an enum backed by `int`. Its value is kept as sent, so a peer's newer value is representable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct AlphaInterpretation(pub i32);

impl AlphaInterpretation {
    pub const COVERAGE: Self = Self(0);
    pub const MASK: Self = Self(1);

    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        Ok(Self(r.i32()?))
    }

    pub fn write(self, w: &mut Writer) {
        w.i32(self.0);
    }
}

/// `android.hardware.graphics.common.BlendMode`: an enum backed by `int`. Its value is kept as sent, so a peer's newer value is representable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct BlendMode(pub i32);

impl BlendMode {
    pub const INVALID: Self = Self(0);
    pub const NONE: Self = Self(1);
    pub const PREMULTIPLIED: Self = Self(2);
    pub const COVERAGE: Self = Self(3);

    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        Ok(Self(r.i32()?))
    }

    pub fn write(self, w: &mut Writer) {
        w.i32(self.0);
    }
}

/// `android.hardware.graphics.common.BufferUsage`: an enum backed by `long`. Its value is kept as sent, so a peer's newer value is representable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct BufferUsage(pub i64);

impl BufferUsage {
    pub const CPU_READ_MASK: Self = Self(15);
    pub const CPU_READ_NEVER: Self = Self(0);
    pub const CPU_READ_RARELY: Self = Self(2);
    pub const CPU_READ_OFTEN: Self = Self(3);
    pub const CPU_WRITE_MASK: Self = Self(240);
    pub const CPU_WRITE_NEVER: Self = Self(0);
    pub const CPU_WRITE_RARELY: Self = Self(32);
    pub const CPU_WRITE_OFTEN: Self = Self(48);
    pub const GPU_TEXTURE: Self = Self(256);
    pub const GPU_RENDER_TARGET: Self = Self(512);
    pub const COMPOSER_OVERLAY: Self = Self(2048);
    pub const COMPOSER_CLIENT_TARGET: Self = Self(4096);
    pub const PROTECTED: Self = Self(16384);
    pub const COMPOSER_CURSOR: Self = Self(32768);
    pub const VIDEO_ENCODER: Self = Self(65536);
    pub const CAMERA_OUTPUT: Self = Self(131072);
    pub const CAMERA_INPUT: Self = Self(262144);
    pub const RENDERSCRIPT: Self = Self(1048576);
    pub const VIDEO_DECODER: Self = Self(4194304);
    pub const SENSOR_DIRECT_DATA: Self = Self(8388608);
    pub const GPU_DATA_BUFFER: Self = Self(16777216);
    pub const GPU_CUBE_MAP: Self = Self(33554432);
    pub const GPU_MIPMAP_COMPLETE: Self = Self(67108864);
    pub const HW_IMAGE_ENCODER: Self = Self(134217728);
    pub const FRONT_BUFFER: Self = Self(4294967296);
    pub const VENDOR_MASK: Self = Self(4026531840);
    pub const VENDOR_MASK_HI: Self = Self(-281474976710656);

    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        Ok(Self(r.i64()?))
    }

    pub fn write(self, w: &mut Writer) {
        w.i64(self.0);
    }
}

/// `android.hardware.graphics.common.ChromaSiting`: an enum backed by `long`. Its value is kept as sent, so a peer's newer value is representable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ChromaSiting(pub i64);

impl ChromaSiting {
    pub const NONE: Self = Self(0);
    pub const UNKNOWN: Self = Self(1);
    pub const SITED_INTERSTITIAL: Self = Self(2);
    pub const COSITED_HORIZONTAL: Self = Self(3);
    pub const COSITED_VERTICAL: Self = Self(4);
    pub const COSITED_BOTH: Self = Self(5);

    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        Ok(Self(r.i64()?))
    }

    pub fn write(self, w: &mut Writer) {
        w.i64(self.0);
    }
}

/// `android.hardware.graphics.common.ColorTransform`: an enum backed by `int`. Its value is kept as sent, so a peer's newer value is representable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ColorTransform(pub i32);

impl ColorTransform {
    pub const IDENTITY: Self = Self(0);
    pub const ARBITRARY_MATRIX: Self = Self(1);
    pub const VALUE_INVERSE: Self = Self(2);
    pub const GRAYSCALE: Self = Self(3);
    pub const CORRECT_PROTANOPIA: Self = Self(4);
    pub const CORRECT_DEUTERANOPIA: Self = Self(5);
    pub const CORRECT_TRITANOPIA: Self = Self(6);

    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        Ok(Self(r.i32()?))
    }

    pub fn write(self, w: &mut Writer) {
        w.i32(self.0);
    }
}

/// `android.hardware.graphics.common.Compression`: an enum backed by `long`. Its value is kept as sent, so a peer's newer value is representable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct Compression(pub i64);

impl Compression {
    pub const NONE: Self = Self(0);
    pub const DISPLAY_STREAM_COMPRESSION: Self = Self(1);

    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        Ok(Self(r.i64()?))
    }

    pub fn write(self, w: &mut Writer) {
        w.i64(self.0);
    }
}

/// `android.hardware.graphics.common.Cta861_3`: a parcelable.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Cta861_3 {
    pub max_content_light_level: f32,
    pub max_frame_average_light_level: f32,
}

impl Cta861_3 {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { r.f32()? } else { Default::default() };
        let v1 = if r.within(end) { r.f32()? } else { Default::default() };
        r.parcelable_end(end)?;
        Ok(Self { max_content_light_level: v0, max_frame_average_light_level: v1 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        w.f32(self.max_content_light_level);
        w.f32(self.max_frame_average_light_level);
        w.parcelable_end(at);
    }

    /// The value anywhere else a Cta861_3 is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null Cta861_3"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}

/// `android.hardware.graphics.common.Dataspace`: an enum backed by `int`. Its value is kept as sent, so a peer's newer value is representable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct Dataspace(pub i32);

impl Dataspace {
    pub const UNKNOWN: Self = Self(0);
    pub const ARBITRARY: Self = Self(1);
    pub const STANDARD_SHIFT: Self = Self(16);
    pub const STANDARD_MASK: Self = Self(4128768);
    pub const STANDARD_UNSPECIFIED: Self = Self(0);
    pub const STANDARD_BT709: Self = Self(65536);
    pub const STANDARD_BT601_625: Self = Self(131072);
    pub const STANDARD_BT601_625_UNADJUSTED: Self = Self(196608);
    pub const STANDARD_BT601_525: Self = Self(262144);
    pub const STANDARD_BT601_525_UNADJUSTED: Self = Self(327680);
    pub const STANDARD_BT2020: Self = Self(393216);
    pub const STANDARD_BT2020_CONSTANT_LUMINANCE: Self = Self(458752);
    pub const STANDARD_BT470M: Self = Self(524288);
    pub const STANDARD_FILM: Self = Self(589824);
    pub const STANDARD_DCI_P3: Self = Self(655360);
    pub const STANDARD_ADOBE_RGB: Self = Self(720896);
    pub const TRANSFER_SHIFT: Self = Self(22);
    pub const TRANSFER_MASK: Self = Self(130023424);
    pub const TRANSFER_UNSPECIFIED: Self = Self(0);
    pub const TRANSFER_LINEAR: Self = Self(4194304);
    pub const TRANSFER_SRGB: Self = Self(8388608);
    pub const TRANSFER_SMPTE_170M: Self = Self(12582912);
    pub const TRANSFER_GAMMA2_2: Self = Self(16777216);
    pub const TRANSFER_GAMMA2_6: Self = Self(20971520);
    pub const TRANSFER_GAMMA2_8: Self = Self(25165824);
    pub const TRANSFER_ST2084: Self = Self(29360128);
    pub const TRANSFER_HLG: Self = Self(33554432);
    pub const RANGE_SHIFT: Self = Self(27);
    pub const RANGE_MASK: Self = Self(939524096);
    pub const RANGE_UNSPECIFIED: Self = Self(0);
    pub const RANGE_FULL: Self = Self(134217728);
    pub const RANGE_LIMITED: Self = Self(268435456);
    pub const RANGE_EXTENDED: Self = Self(402653184);
    pub const SRGB_LINEAR: Self = Self(138477568);
    pub const SCRGB_LINEAR: Self = Self(406913024);
    pub const SRGB: Self = Self(142671872);
    pub const SCRGB: Self = Self(411107328);
    pub const JFIF: Self = Self(146931712);
    pub const BT601_625: Self = Self(281149440);
    pub const BT601_525: Self = Self(281280512);
    pub const BT709: Self = Self(281083904);
    pub const DCI_P3_LINEAR: Self = Self(139067392);
    pub const DCI_P3: Self = Self(155844608);
    pub const DISPLAY_P3_LINEAR: Self = Self(139067392);
    pub const DISPLAY_P3: Self = Self(143261696);
    pub const ADOBE_RGB: Self = Self(151715840);
    pub const ADOBE_RGB_LINEAR: Self = Self(139132928);
    pub const BT2020_LINEAR: Self = Self(138805248);
    pub const BT2020: Self = Self(147193856);
    pub const BT2020_PQ: Self = Self(163971072);
    pub const BT2020_LINEAR_EXTENDED: Self = Self(407240704);
    pub const DEPTH: Self = Self(4096);
    pub const SENSOR: Self = Self(4097);
    pub const BT2020_ITU: Self = Self(281411584);
    pub const BT2020_ITU_PQ: Self = Self(298188800);
    pub const BT2020_ITU_HLG: Self = Self(302383104);
    pub const BT2020_HLG: Self = Self(168165376);
    pub const DISPLAY_BT2020: Self = Self(142999552);
    pub const DYNAMIC_DEPTH: Self = Self(4098);
    pub const JPEG_APP_SEGMENTS: Self = Self(4099);
    pub const HEIF: Self = Self(4100);
    pub const JPEG_R: Self = Self(4101);
    pub const BT709_FULL_RANGE: Self = Self(146866176);

    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        Ok(Self(r.i32()?))
    }

    pub fn write(self, w: &mut Writer) {
        w.i32(self.0);
    }
}

/// `android.hardware.graphics.common.DisplayDecorationSupport`: a parcelable.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct DisplayDecorationSupport {
    pub format: PixelFormat,
    pub alpha_interpretation: AlphaInterpretation,
}

impl DisplayDecorationSupport {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { PixelFormat::read(r)? } else { Default::default() };
        let v1 = if r.within(end) { AlphaInterpretation::read(r)? } else { Default::default() };
        r.parcelable_end(end)?;
        Ok(Self { format: v0, alpha_interpretation: v1 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        self.format.write(w);
        self.alpha_interpretation.write(w);
        w.parcelable_end(at);
    }

    /// The value anywhere else a DisplayDecorationSupport is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null DisplayDecorationSupport"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}

/// `android.hardware.graphics.common.DisplayHotplugEvent`: an enum backed by `int`. Its value is kept as sent, so a peer's newer value is representable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct DisplayHotplugEvent(pub i32);

impl DisplayHotplugEvent {
    pub const CONNECTED: Self = Self(0);
    pub const DISCONNECTED: Self = Self(1);
    pub const ERROR_UNKNOWN: Self = Self(-1);
    pub const ERROR_INCOMPATIBLE_CABLE: Self = Self(-2);
    pub const ERROR_TOO_MANY_DISPLAYS: Self = Self(-3);

    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        Ok(Self(r.i32()?))
    }

    pub fn write(self, w: &mut Writer) {
        w.i32(self.0);
    }
}

/// `android.hardware.graphics.common.ExtendableType`: a parcelable.
#[derive(Debug, Clone, PartialEq)]
pub struct ExtendableType {
    pub name: String,
    pub value: i64,
}

impl Default for ExtendableType {
    fn default() -> Self {
        Self {
            name: Default::default(),
            value: 0,
        }
    }
}

impl ExtendableType {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { r.string16()?.ok_or(Malformed("a null string"))? } else { Default::default() };
        let v1 = if r.within(end) { r.i64()? } else { 0 };
        r.parcelable_end(end)?;
        Ok(Self { name: v0, value: v1 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        w.string16(&self.name);
        w.i64(self.value);
        w.parcelable_end(at);
    }

    /// The value anywhere else a ExtendableType is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null ExtendableType"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}

/// `android.hardware.graphics.common.FRect`: a parcelable.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct FRect {
    pub left: f32,
    pub top: f32,
    pub right: f32,
    pub bottom: f32,
}

impl FRect {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { r.f32()? } else { Default::default() };
        let v1 = if r.within(end) { r.f32()? } else { Default::default() };
        let v2 = if r.within(end) { r.f32()? } else { Default::default() };
        let v3 = if r.within(end) { r.f32()? } else { Default::default() };
        r.parcelable_end(end)?;
        Ok(Self { left: v0, top: v1, right: v2, bottom: v3 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        w.f32(self.left);
        w.f32(self.top);
        w.f32(self.right);
        w.f32(self.bottom);
        w.parcelable_end(at);
    }

    /// The value anywhere else a FRect is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null FRect"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}

/// `android.hardware.graphics.common.HardwareBuffer`: a parcelable.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct HardwareBuffer {
    pub description: HardwareBufferDescription,
    pub handle: android_hardware_common::NativeHandle,
}

impl HardwareBuffer {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { HardwareBufferDescription::read_value(r)? } else { Default::default() };
        let v1 = if r.within(end) { android_hardware_common::NativeHandle::read_value(r)? } else { Default::default() };
        r.parcelable_end(end)?;
        Ok(Self { description: v0, handle: v1 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        self.description.write_value(w);
        self.handle.write_value(w);
        w.parcelable_end(at);
    }

    /// The value anywhere else a HardwareBuffer is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null HardwareBuffer"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}

/// `android.hardware.graphics.common.HardwareBufferDescription`: a parcelable.
#[derive(Debug, Clone, PartialEq)]
pub struct HardwareBufferDescription {
    pub width: i32,
    pub height: i32,
    pub layers: i32,
    pub format: PixelFormat,
    pub usage: BufferUsage,
    pub stride: i32,
}

impl Default for HardwareBufferDescription {
    fn default() -> Self {
        Self {
            width: Default::default(),
            height: Default::default(),
            layers: Default::default(),
            format: PixelFormat::UNSPECIFIED,
            usage: BufferUsage::CPU_READ_NEVER,
            stride: Default::default(),
        }
    }
}

impl HardwareBufferDescription {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { r.i32()? } else { Default::default() };
        let v1 = if r.within(end) { r.i32()? } else { Default::default() };
        let v2 = if r.within(end) { r.i32()? } else { Default::default() };
        let v3 = if r.within(end) { PixelFormat::read(r)? } else { PixelFormat::UNSPECIFIED };
        let v4 = if r.within(end) { BufferUsage::read(r)? } else { BufferUsage::CPU_READ_NEVER };
        let v5 = if r.within(end) { r.i32()? } else { Default::default() };
        r.parcelable_end(end)?;
        Ok(Self { width: v0, height: v1, layers: v2, format: v3, usage: v4, stride: v5 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        w.i32(self.width);
        w.i32(self.height);
        w.i32(self.layers);
        self.format.write(w);
        self.usage.write(w);
        w.i32(self.stride);
        w.parcelable_end(at);
    }

    /// The value anywhere else a HardwareBufferDescription is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null HardwareBufferDescription"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}

/// `android.hardware.graphics.common.Hdr`: an enum backed by `int`. Its value is kept as sent, so a peer's newer value is representable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct Hdr(pub i32);

impl Hdr {
    pub const INVALID: Self = Self(0);
    pub const DOLBY_VISION: Self = Self(1);
    pub const HDR10: Self = Self(2);
    pub const HLG: Self = Self(3);
    pub const HDR10_PLUS: Self = Self(4);
    pub const DOLBY_VISION_4K30: Self = Self(5);

    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        Ok(Self(r.i32()?))
    }

    pub fn write(self, w: &mut Writer) {
        w.i32(self.0);
    }
}

/// `android.hardware.graphics.common.HdrConversionCapability`: a parcelable.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct HdrConversionCapability {
    pub source_type: Hdr,
    pub output_type: Hdr,
    pub adds_latency: bool,
}

impl HdrConversionCapability {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { Hdr::read(r)? } else { Default::default() };
        let v1 = if r.within(end) { Hdr::read(r)? } else { Default::default() };
        let v2 = if r.within(end) { r.bool()? } else { Default::default() };
        r.parcelable_end(end)?;
        Ok(Self { source_type: v0, output_type: v1, adds_latency: v2 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        self.source_type.write(w);
        self.output_type.write(w);
        w.bool(self.adds_latency);
        w.parcelable_end(at);
    }

    /// The value anywhere else a HdrConversionCapability is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null HdrConversionCapability"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}

/// `android.hardware.graphics.common.HdrConversionStrategy`: a union.
#[derive(Debug, Clone, PartialEq)]
pub enum HdrConversionStrategy {
    Passthrough(bool),
    AutoAllowedHdrTypes(Vec<Hdr>),
    ForceHdrConversion(Hdr),
}

impl Default for HdrConversionStrategy {
    fn default() -> Self {
        Self::Passthrough(true)
    }
}

impl HdrConversionStrategy {
    /// The field's tag: its index in the declaration.
    pub fn tag(&self) -> i32 {
        match self {
            Self::Passthrough(_) => 0,
            Self::AutoAllowedHdrTypes(_) => 1,
            Self::ForceHdrConversion(_) => 2,
        }
    }

    /// The union's body (after its marker): its tag, then that field.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        r.enter()?;
        let v = match r.i32()? {
            0 => Self::Passthrough(r.bool()?),
            1 => Self::AutoAllowedHdrTypes(r.i32_array()?.map(|v| v.into_iter().map(Hdr).collect::<Vec<_>>()).ok_or(Malformed("a null array"))?),
            2 => Self::ForceHdrConversion(Hdr::read(r)?),
            _ => return Err(Malformed("an unknown HdrConversionStrategy tag")),
        };
        r.leave();
        Ok(v)
    }

    /// The union's body: its tag, then that field.
    pub fn write(&self, w: &mut Writer) {
        match self {
            Self::Passthrough(v) => {
                w.i32(0);
                w.bool((*v));
            }
            Self::AutoAllowedHdrTypes(v) => {
                w.i32(1);
                w.i32_array(&(*v).iter().map(|x| x.0).collect::<Vec<_>>());
            }
            Self::ForceHdrConversion(v) => {
                w.i32(2);
                (*v).write(w);
            }
        }
    }

    /// The value anywhere else a HdrConversionStrategy is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null HdrConversionStrategy"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}

/// `android.hardware.graphics.common.Interlaced`: an enum backed by `long`. Its value is kept as sent, so a peer's newer value is representable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct Interlaced(pub i64);

impl Interlaced {
    pub const NONE: Self = Self(0);
    pub const TOP_BOTTOM: Self = Self(1);
    pub const RIGHT_LEFT: Self = Self(2);

    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        Ok(Self(r.i64()?))
    }

    pub fn write(self, w: &mut Writer) {
        w.i64(self.0);
    }
}

/// `android.hardware.graphics.common.PixelFormat`: an enum backed by `int`. Its value is kept as sent, so a peer's newer value is representable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct PixelFormat(pub i32);

impl PixelFormat {
    pub const UNSPECIFIED: Self = Self(0);
    pub const RGBA_8888: Self = Self(1);
    pub const RGBX_8888: Self = Self(2);
    pub const RGB_888: Self = Self(3);
    pub const RGB_565: Self = Self(4);
    pub const BGRA_8888: Self = Self(5);
    pub const YCBCR_422_SP: Self = Self(16);
    pub const YCRCB_420_SP: Self = Self(17);
    pub const YCBCR_422_I: Self = Self(20);
    pub const RGBA_FP16: Self = Self(22);
    pub const RAW16: Self = Self(32);
    pub const BLOB: Self = Self(33);
    pub const IMPLEMENTATION_DEFINED: Self = Self(34);
    pub const YCBCR_420_888: Self = Self(35);
    pub const RAW_OPAQUE: Self = Self(36);
    pub const RAW10: Self = Self(37);
    pub const RAW12: Self = Self(38);
    pub const RGBA_1010102: Self = Self(43);
    pub const Y8: Self = Self(538982489);
    pub const Y16: Self = Self(540422489);
    pub const YV12: Self = Self(842094169);
    pub const DEPTH_16: Self = Self(48);
    pub const DEPTH_24: Self = Self(49);
    pub const DEPTH_24_STENCIL_8: Self = Self(50);
    pub const DEPTH_32F: Self = Self(51);
    pub const DEPTH_32F_STENCIL_8: Self = Self(52);
    pub const STENCIL_8: Self = Self(53);
    pub const YCBCR_P010: Self = Self(54);
    pub const HSV_888: Self = Self(55);
    pub const R_8: Self = Self(56);
    pub const R_16_UINT: Self = Self(57);
    pub const RG_1616_UINT: Self = Self(58);
    pub const RGBA_10101010: Self = Self(59);

    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        Ok(Self(r.i32()?))
    }

    pub fn write(self, w: &mut Writer) {
        w.i32(self.0);
    }
}

/// `android.hardware.graphics.common.PlaneLayout`: a parcelable.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct PlaneLayout {
    pub components: Vec<PlaneLayoutComponent>,
    pub offset_in_bytes: i64,
    pub sample_increment_in_bits: i64,
    pub stride_in_bytes: i64,
    pub width_in_samples: i64,
    pub height_in_samples: i64,
    pub total_size_in_bytes: i64,
    pub horizontal_subsampling: i64,
    pub vertical_subsampling: i64,
}

impl PlaneLayout {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { read_vec(r, |r| Ok(PlaneLayoutComponent::read_value(r)?))?.ok_or(Malformed("a null array"))? } else { Default::default() };
        let v1 = if r.within(end) { r.i64()? } else { Default::default() };
        let v2 = if r.within(end) { r.i64()? } else { Default::default() };
        let v3 = if r.within(end) { r.i64()? } else { Default::default() };
        let v4 = if r.within(end) { r.i64()? } else { Default::default() };
        let v5 = if r.within(end) { r.i64()? } else { Default::default() };
        let v6 = if r.within(end) { r.i64()? } else { Default::default() };
        let v7 = if r.within(end) { r.i64()? } else { Default::default() };
        let v8 = if r.within(end) { r.i64()? } else { Default::default() };
        r.parcelable_end(end)?;
        Ok(Self { components: v0, offset_in_bytes: v1, sample_increment_in_bits: v2, stride_in_bytes: v3, width_in_samples: v4, height_in_samples: v5, total_size_in_bytes: v6, horizontal_subsampling: v7, vertical_subsampling: v8 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        w.i32(self.components.len() as i32);
        for x1 in self.components.iter() {
            (*x1).write_value(w);
        }
        w.i64(self.offset_in_bytes);
        w.i64(self.sample_increment_in_bits);
        w.i64(self.stride_in_bytes);
        w.i64(self.width_in_samples);
        w.i64(self.height_in_samples);
        w.i64(self.total_size_in_bytes);
        w.i64(self.horizontal_subsampling);
        w.i64(self.vertical_subsampling);
        w.parcelable_end(at);
    }

    /// The value anywhere else a PlaneLayout is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null PlaneLayout"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}

/// `android.hardware.graphics.common.PlaneLayoutComponent`: a parcelable.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct PlaneLayoutComponent {
    pub r#type: ExtendableType,
    pub offset_in_bits: i64,
    pub size_in_bits: i64,
}

impl PlaneLayoutComponent {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { ExtendableType::read_value(r)? } else { Default::default() };
        let v1 = if r.within(end) { r.i64()? } else { Default::default() };
        let v2 = if r.within(end) { r.i64()? } else { Default::default() };
        r.parcelable_end(end)?;
        Ok(Self { r#type: v0, offset_in_bits: v1, size_in_bits: v2 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        self.r#type.write_value(w);
        w.i64(self.offset_in_bits);
        w.i64(self.size_in_bits);
        w.parcelable_end(at);
    }

    /// The value anywhere else a PlaneLayoutComponent is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null PlaneLayoutComponent"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}

/// `android.hardware.graphics.common.PlaneLayoutComponentType`: an enum backed by `long`. Its value is kept as sent, so a peer's newer value is representable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct PlaneLayoutComponentType(pub i64);

impl PlaneLayoutComponentType {
    pub const Y: Self = Self(1);
    pub const CB: Self = Self(2);
    pub const CR: Self = Self(4);
    pub const R: Self = Self(1024);
    pub const G: Self = Self(2048);
    pub const B: Self = Self(4096);
    pub const RAW: Self = Self(1048576);
    pub const A: Self = Self(1073741824);

    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        Ok(Self(r.i64()?))
    }

    pub fn write(self, w: &mut Writer) {
        w.i64(self.0);
    }
}

/// `android.hardware.graphics.common.Point`: a parcelable.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Point {
    pub x: i32,
    pub y: i32,
}

impl Point {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { r.i32()? } else { Default::default() };
        let v1 = if r.within(end) { r.i32()? } else { Default::default() };
        r.parcelable_end(end)?;
        Ok(Self { x: v0, y: v1 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        w.i32(self.x);
        w.i32(self.y);
        w.parcelable_end(at);
    }

    /// The value anywhere else a Point is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null Point"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}

/// `android.hardware.graphics.common.Rect`: a parcelable.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Rect {
    pub left: i32,
    pub top: i32,
    pub right: i32,
    pub bottom: i32,
}

impl Rect {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { r.i32()? } else { Default::default() };
        let v1 = if r.within(end) { r.i32()? } else { Default::default() };
        let v2 = if r.within(end) { r.i32()? } else { Default::default() };
        let v3 = if r.within(end) { r.i32()? } else { Default::default() };
        r.parcelable_end(end)?;
        Ok(Self { left: v0, top: v1, right: v2, bottom: v3 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        w.i32(self.left);
        w.i32(self.top);
        w.i32(self.right);
        w.i32(self.bottom);
        w.parcelable_end(at);
    }

    /// The value anywhere else a Rect is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null Rect"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}

/// `android.hardware.graphics.common.Smpte2086`: a parcelable.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Smpte2086 {
    pub primary_red: XyColor,
    pub primary_green: XyColor,
    pub primary_blue: XyColor,
    pub white_point: XyColor,
    pub max_luminance: f32,
    pub min_luminance: f32,
}

impl Smpte2086 {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { XyColor::read_value(r)? } else { Default::default() };
        let v1 = if r.within(end) { XyColor::read_value(r)? } else { Default::default() };
        let v2 = if r.within(end) { XyColor::read_value(r)? } else { Default::default() };
        let v3 = if r.within(end) { XyColor::read_value(r)? } else { Default::default() };
        let v4 = if r.within(end) { r.f32()? } else { Default::default() };
        let v5 = if r.within(end) { r.f32()? } else { Default::default() };
        r.parcelable_end(end)?;
        Ok(Self { primary_red: v0, primary_green: v1, primary_blue: v2, white_point: v3, max_luminance: v4, min_luminance: v5 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        self.primary_red.write_value(w);
        self.primary_green.write_value(w);
        self.primary_blue.write_value(w);
        self.white_point.write_value(w);
        w.f32(self.max_luminance);
        w.f32(self.min_luminance);
        w.parcelable_end(at);
    }

    /// The value anywhere else a Smpte2086 is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null Smpte2086"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}

/// `android.hardware.graphics.common.StandardMetadataType`: an enum backed by `long`. Its value is kept as sent, so a peer's newer value is representable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct StandardMetadataType(pub i64);

impl StandardMetadataType {
    pub const INVALID: Self = Self(0);
    pub const BUFFER_ID: Self = Self(1);
    pub const NAME: Self = Self(2);
    pub const WIDTH: Self = Self(3);
    pub const HEIGHT: Self = Self(4);
    pub const LAYER_COUNT: Self = Self(5);
    pub const PIXEL_FORMAT_REQUESTED: Self = Self(6);
    pub const PIXEL_FORMAT_FOURCC: Self = Self(7);
    pub const PIXEL_FORMAT_MODIFIER: Self = Self(8);
    pub const USAGE: Self = Self(9);
    pub const ALLOCATION_SIZE: Self = Self(10);
    pub const PROTECTED_CONTENT: Self = Self(11);
    pub const COMPRESSION: Self = Self(12);
    pub const INTERLACED: Self = Self(13);
    pub const CHROMA_SITING: Self = Self(14);
    pub const PLANE_LAYOUTS: Self = Self(15);
    pub const CROP: Self = Self(16);
    pub const DATASPACE: Self = Self(17);
    pub const BLEND_MODE: Self = Self(18);
    pub const SMPTE2086: Self = Self(19);
    pub const CTA861_3: Self = Self(20);
    pub const SMPTE2094_40: Self = Self(21);
    pub const SMPTE2094_10: Self = Self(22);
    pub const STRIDE: Self = Self(23);

    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        Ok(Self(r.i64()?))
    }

    pub fn write(self, w: &mut Writer) {
        w.i64(self.0);
    }
}

/// `android.hardware.graphics.common.Transform`: an enum backed by `int`. Its value is kept as sent, so a peer's newer value is representable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct Transform(pub i32);

impl Transform {
    pub const NONE: Self = Self(0);
    pub const FLIP_H: Self = Self(1);
    pub const FLIP_V: Self = Self(2);
    pub const ROT_90: Self = Self(4);
    pub const ROT_180: Self = Self(3);
    pub const ROT_270: Self = Self(7);

    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        Ok(Self(r.i32()?))
    }

    pub fn write(self, w: &mut Writer) {
        w.i32(self.0);
    }
}

/// `android.hardware.graphics.common.XyColor`: a parcelable.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct XyColor {
    pub x: f32,
    pub y: f32,
}

impl XyColor {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { r.f32()? } else { Default::default() };
        let v1 = if r.within(end) { r.f32()? } else { Default::default() };
        r.parcelable_end(end)?;
        Ok(Self { x: v0, y: v1 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        w.f32(self.x);
        w.f32(self.y);
        w.parcelable_end(at);
    }

    /// The value anywhere else a XyColor is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null XyColor"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}
