// generated by tools/gen_aidl.py -- do not edit
//! `android.hardware.common` V2, from the frozen AIDL API in `tools/aidl/android.hardware.common/2/` (interface hash `c32ddfdeb69c6e4a8a45519e6f9a39c4b66fd99f`).
#![allow(
    non_camel_case_types,
    non_upper_case_globals,
    dead_code,
    unused_imports,
    unused_variables,
    unused_parens,
    clippy::all,
    clippy::pedantic
)]

use std::sync::Arc;

use crate::binder::{Broker, HostCall, HostReply};
use crate::hal::aidl::runtime::*;
use crate::hal::parcel::{Malformed, Reader, Writer};
use crate::hal::aidl::{android_hardware_graphics_common, android_hardware_graphics_composer3};

/// `android.hardware.common.Ashmem`: a parcelable.
#[derive(Debug, Clone, PartialEq)]
pub struct Ashmem {
    pub fd: Fd,
    pub size: i64,
}

impl Ashmem {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { Fd::read(r)? } else { return Err(Malformed("Ashmem.fd is missing")) };
        let v1 = if r.within(end) { r.i64()? } else { Default::default() };
        r.parcelable_end(end)?;
        Ok(Self { fd: v0, size: v1 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        self.fd.write(w);
        w.i64(self.size);
        w.parcelable_end(at);
    }

    /// The value anywhere else a Ashmem is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null Ashmem"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}

/// `android.hardware.common.MappableFile`: a parcelable.
#[derive(Debug, Clone, PartialEq)]
pub struct MappableFile {
    pub length: i64,
    pub prot: i32,
    pub fd: Fd,
    pub offset: i64,
}

impl MappableFile {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { r.i64()? } else { Default::default() };
        let v1 = if r.within(end) { r.i32()? } else { Default::default() };
        let v2 = if r.within(end) { Fd::read(r)? } else { return Err(Malformed("MappableFile.fd is missing")) };
        let v3 = if r.within(end) { r.i64()? } else { Default::default() };
        r.parcelable_end(end)?;
        Ok(Self { length: v0, prot: v1, fd: v2, offset: v3 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        w.i64(self.length);
        w.i32(self.prot);
        self.fd.write(w);
        w.i64(self.offset);
        w.parcelable_end(at);
    }

    /// The value anywhere else a MappableFile is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null MappableFile"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}

/// `android.hardware.common.NativeHandle`: a parcelable.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct NativeHandle {
    pub fds: Vec<Fd>,
    pub ints: Vec<i32>,
}

impl NativeHandle {
    /// The parcelable's body (after its marker): its size, then its fields; fields an older
    /// writer did not send keep their defaults, and fields a newer writer added are skipped.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        let end = r.parcelable_body()?;
        let v0 = if r.within(end) { read_vec(r, |r| Ok(Fd::read(r)?))?.ok_or(Malformed("a null array"))? } else { Default::default() };
        let v1 = if r.within(end) { r.i32_array()?.ok_or(Malformed("a null array"))? } else { Default::default() };
        r.parcelable_end(end)?;
        Ok(Self { fds: v0, ints: v1 })
    }

    /// The parcelable's body: its size, then its fields.
    pub fn write(&self, w: &mut Writer) {
        let at = w.parcelable_body_start();
        w.i32(self.fds.len() as i32);
        for x1 in self.fds.iter() {
            (*x1).write(w);
        }
        w.i32_array(&self.ints);
        w.parcelable_end(at);
    }

    /// The value anywhere else a NativeHandle is: its non-null marker, then [`Self::read`].
    pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        if !r.marker()? {
            return Err(Malformed("a null NativeHandle"));
        }
        Self::read(r)
    }

    /// A `@nullable` value: its marker (0 for null), then [`Self::read`].
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        if r.marker()? {
            Ok(Some(Self::read(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn write_value(&self, w: &mut Writer) {
        w.marker(true);
        self.write(w);
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        match v {
            Some(v) => v.write_value(w),
            None => w.marker(false),
        }
    }
}
