// generated by tools/gen_aidl.py -- do not edit
//! AIDL interfaces served or called by the host, generated from the frozen API files under
//! `tools/aidl` by `tools/gen_aidl.py`; what they share is `runtime.rs` (hand-written).

mod runtime;

pub use runtime::*;

pub mod android_hardware_common;
pub mod android_hardware_graphics_common;
pub mod android_hardware_graphics_composer3;
