//! What every generated AIDL module shares (hand-written; the package modules and `mod.rs` are
//! generated by `tools/gen_aidl.py`): the call context a server sees, `binder::Status`, the file
//! descriptor and binder values, a proxy's errors, and the transactions libbinder answers for every
//! binder.
use std::fmt;
use std::sync::Arc;

use crate::binder::{HostCall, HostReply};
use crate::errno::Errno;
use crate::fd::OpenFile;
use crate::hal::parcel::{Malformed, Reader, Writer, EX_HAS_REPLY_HEADER, EX_ILLEGAL_ARGUMENT, EX_SERVICE_SPECIFIC, EX_UNSUPPORTED_OPERATION};

/// AIDL's meta-transactions (`FIRST_CALL_TRANSACTION + 16777214` and `+ 16777213`), which every
/// generated dispatcher answers from its frozen version and hash.
pub const GET_INTERFACE_VERSION: u32 = 0x00ff_ffff;
pub const GET_INTERFACE_HASH: u32 = 0x00ff_fffe;
/// The last user transaction code (`IBinder::LAST_CALL_TRANSACTION`).
pub const LAST_CALL_TRANSACTION: u32 = 0x00ff_ffff;
/// libbinder's `IBinder::INTERFACE_TRANSACTION` (`'_NTF'`), `PING_TRANSACTION` (`'_PNG'`) and
/// `EXTENSION_TRANSACTION` (`'_EXT'`), which `BBinder` answers for every binder.
pub const INTERFACE_TRANSACTION: u32 = 0x5f4e_5446;
pub const PING_TRANSACTION: u32 = 0x5f50_4e47;
pub const EXTENSION_TRANSACTION: u32 = 0x5f45_5854;

/// The transaction a server method is answering: who sent it (`call.sender_pid`,
/// `call.sender_euid`) and the objects it carried.
pub struct Ctx<'a> {
    pub call: &'a HostCall,
}

/// A method's failure, as `binder::Status` carries it to the caller.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Status {
    /// `EX_SERVICE_SPECIFIC` with the interface's own error code.
    ServiceSpecific(i32),
    /// Any other exception (`EX_ILLEGAL_ARGUMENT`, `EX_UNSUPPORTED_OPERATION`, ...) and its message.
    Exception(i32, String),
}

impl Status {
    /// What a server method nobody implemented answers.
    #[must_use]
    pub fn unimplemented(method: &str) -> Self {
        Self::Exception(EX_UNSUPPORTED_OPERATION, format!("{method} is not implemented"))
    }

    /// `binder::Status::writeToParcel` of this failure.
    pub fn write(&self, w: &mut Writer) {
        match self {
            Self::ServiceSpecific(code) => w.exception(EX_SERVICE_SPECIFIC, "", Some(*code)),
            Self::Exception(EX_SERVICE_SPECIFIC, message) => w.exception(EX_SERVICE_SPECIFIC, message, Some(0)),
            Self::Exception(code, message) => w.exception(*code, message, None),
        }
    }

    /// `binder::Status::readFromParcel`: a reply's status header, `Ok` for `EX_NONE` (or a fat
    /// reply header, which native code skips).
    ///
    /// # Errors
    /// A header that does not parse.
    pub fn read(r: &mut Reader<'_>) -> Result<Result<(), Status>, Malformed> {
        let code = r.i32()?;
        if code == 0 {
            return Ok(Ok(()));
        }
        if code == EX_HAS_REPLY_HEADER {
            let size = usize::try_from(r.i32()?).map_err(|_| Malformed("negative reply header size"))?;
            r.skip(size.checked_sub(4).ok_or(Malformed("reply header size below its header"))?)?;
            return Ok(Ok(()));
        }
        let message = r.string16()?.unwrap_or_default();
        let trace = usize::try_from(r.i32()?).map_err(|_| Malformed("negative stack trace size"))?;
        r.skip(trace)?;
        if code == EX_SERVICE_SPECIFIC {
            return Ok(Err(Self::ServiceSpecific(r.i32()?)));
        }
        Ok(Err(Self::Exception(code, message)))
    }
}

/// A `ParcelFileDescriptor`: the open file the transaction carried (or the host sends).
#[derive(Clone)]
pub struct Fd(pub Arc<OpenFile>);

impl fmt::Debug for Fd {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Fd({:p})", Arc::as_ptr(&self.0))
    }
}

/// The same open file.
impl PartialEq for Fd {
    fn eq(&self, other: &Self) -> bool {
        Arc::ptr_eq(&self.0, &other.0)
    }
}

impl Eq for Fd {}

impl Fd {
    /// A required `ParcelFileDescriptor`.
    ///
    /// # Errors
    /// A null one, or one the parcel does not hold.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        r.file()?.map(Self).ok_or(Malformed("a null file descriptor"))
    }

    /// A `@nullable ParcelFileDescriptor`.
    ///
    /// # Errors
    /// One the parcel does not hold.
    pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {
        Ok(r.file()?.map(Self))
    }

    pub fn write(&self, w: &mut Writer) {
        w.file(Arc::clone(&self.0));
    }

    pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {
        w.nullable_file(v.map(|f| Arc::clone(&f.0)));
    }
}

/// An `IBinder` or interface value.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum Binder {
    #[default]
    Null,
    /// A binder the host holds a handle to (in its table): one a transaction brought, which the
    /// host may call through a generated proxy.
    Handle(u32),
    /// A host service, by the `ptr` `Broker::create_host_service_objects` gave it.
    Host(u64),
}

impl Binder {
    /// A `@nullable` binder: [`Self::Null`] for null.
    ///
    /// # Errors
    /// One the parcel does not hold.
    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        Ok(r.binder()?.map_or(Self::Null, Self::Handle))
    }

    /// A required binder.
    ///
    /// # Errors
    /// A null one, or one the parcel does not hold.
    pub fn read_required(r: &mut Reader<'_>) -> Result<Self, Malformed> {
        match Self::read(r)? {
            Self::Null => Err(Malformed("a null binder")),
            b => Ok(b),
        }
    }

    /// `writeStrongBinder` of this binder, with the stability it is written with.
    pub fn write(&self, w: &mut Writer, stability: i32) {
        match *self {
            Self::Null => w.null_binder(),
            Self::Handle(h) => w.handle(h, stability),
            Self::Host(ptr) => w.binder(ptr, stability),
        }
    }
}

/// Why a generated proxy's call failed.
#[derive(Debug, Clone, PartialEq)]
pub enum CallError {
    /// The transaction did not happen (`Broker::host_transact`'s error).
    Transport(Errno),
    /// The callee answered with an exception.
    Status(Status),
    /// The reply did not parse.
    Malformed(Malformed),
    /// The request carries file descriptors, which the host's transactions cannot send yet.
    Files,
}

impl From<Malformed> for CallError {
    fn from(m: Malformed) -> Self {
        Self::Malformed(m)
    }
}

/// An array of values each read by `f`: its length (-1 for null), then the elements.
///
/// # Errors
/// A length the parcel cannot hold, or an element `f` refuses.
pub fn read_vec<'a, T>(r: &mut Reader<'a>, mut f: impl FnMut(&mut Reader<'a>) -> Result<T, Malformed>) -> Result<Option<Vec<T>>, Malformed> {
    // Every element that is not a primitive takes at least 4 bytes (a marker or a length).
    let Some(len) = r.array_len(4)? else { return Ok(None) };
    let mut v = Vec::new();
    for _ in 0..len {
        v.push(f(r)?);
    }
    Ok(Some(v))
}

/// A fixed-size array (`T[N]`): written as any array, and refused unless it has `len` elements.
///
/// # Errors
/// Another length.
pub fn fixed_len<T>(v: Option<Vec<T>>, len: usize) -> Result<Option<Vec<T>>, Malformed> {
    match v {
        Some(v) if v.len() != len => Err(Malformed("a fixed-size array of another size")),
        v => Ok(v),
    }
}

/// The offsets of a request's binder objects, for `Broker::host_transact`.
///
/// # Errors
/// [`CallError::Files`] when the request carries file descriptors: the host's transactions send
/// binder objects only.
pub fn request_offsets(w: &Writer) -> Result<Vec<u64>, CallError> {
    if !w.fds.is_empty() {
        return Err(CallError::Files);
    }
    Ok(w.binders.iter().map(|&o| o as u64).collect())
}

/// A reply's status header: `Ok`, or the callee's exception as an error.
///
/// # Errors
/// The exception, or a header that does not parse.
pub fn reply_status(r: &mut Reader<'_>) -> Result<(), CallError> {
    Status::read(r)?.map_err(CallError::Status)
}

/// What `BBinder` answers itself, before any interface sees a transaction: its descriptor, a
/// ping, and a null extension. `None` for any other code.
#[must_use]
pub fn meta_reply(code: u32, descriptor: &str) -> Option<HostReply> {
    let mut w = Writer::new();
    match code {
        INTERFACE_TRANSACTION => w.string16(descriptor),
        PING_TRANSACTION => {}
        EXTENSION_TRANSACTION => w.null_binder(),
        _ => return None,
    }
    Some(w.into_reply())
}

/// Whether `code` is a user transaction (`FIRST_CALL_TRANSACTION..=LAST_CALL_TRANSACTION`), for
/// which libbinder checks the interface token before the interface sees it.
#[must_use]
pub fn is_user_code(code: u32) -> bool {
    (1..=LAST_CALL_TRANSACTION).contains(&code)
}

/// The reply to a request that did not parse: `EX_ILLEGAL_ARGUMENT`. (libbinder fails such a
/// transaction with a `status_t` such as `BAD_VALUE`, which a `HostReply` cannot carry.)
#[must_use]
pub fn illegal_argument(m: &Malformed) -> HostReply {
    let mut w = Writer::new();
    w.exception(EX_ILLEGAL_ARGUMENT, m.0, None);
    w.into_reply()
}

/// The reply to a code the interface does not have. libbinder answers one with the `status_t`
/// `UNKNOWN_TRANSACTION` and no reply parcel; a `HostReply` cannot carry a `status_t` yet, so this
/// is `EX_UNSUPPORTED_OPERATION`, which an AIDL caller reports the same way (a failed call).
#[must_use]
pub fn unknown_transaction() -> HostReply {
    let mut w = Writer::new();
    w.exception(EX_UNSUPPORTED_OPERATION, "unknown transaction", None);
    w.into_reply()
}
