#!/usr/bin/env python3
"""Generate the guest half of omnidroid's GLES forwarding (the GL fallback of the real-AOSP path).

    python3 tools/gen_gl_forward.py        (writes crates/omni-linux/device/src/gl/generated.c)

The command list is `crates/omni-android/src/gles/signatures.rs` -- itself generated from the
Khronos registries by `tools/gen_gles_signatures.py` -- so the guest's forwarders and the host's
typed callers (`omni-linux`'s `gpu::gl`, which includes that same file) can never disagree on a
command's shape. Only its `gl*` commands are forwarded here; EGL is the guest driver's own
(`egl.c`).

A command's id is its index among the table's `gl*` commands, in the table's order. The table's
**fingerprint** (FNV-1a 64 over `name:params:ret;` of those commands, in order) is compiled into
the guest driver and sent to the host at `eglInitialize`; the host computes the same over the table
it was built with and refuses a driver built from another one.

Each forwarder takes its parameters in their AAPCS64 classes: an integer or pointer as a 64-bit
value (the host truncates it to the command's exact width, so the upper bits a caller leaves
unspecified for a narrow argument are never read), a `float` or `double` as itself, whose bits are
sent. Its return is likewise a 64-bit integer, a `float` or nothing.

Commands in `SPECIAL` are the driver's own (`gl_special.c`): what returns host memory (strings,
buffer maps) or takes a guest function (debug callbacks), and the EGLImage targets.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABLE = os.path.join(ROOT, "crates", "omni-android", "src", "gles", "signatures.rs")
OUT = os.path.join(ROOT, "crates", "omni-linux", "device", "src", "gl", "generated.c")

# Implemented by hand in gl_special.c (the host-side counterparts are in `gpu::gl`).
SPECIAL = {
    "glGetString", "glGetStringi",
    "glMapBufferRange", "glMapBufferRangeEXT", "glMapBufferOES", "glUnmapBuffer", "glUnmapBufferOES",
    "glFlushMappedBufferRange", "glFlushMappedBufferRangeEXT", "glGetBufferPointerv", "glGetBufferPointervOES",
    "glDebugMessageCallback", "glDebugMessageCallbackKHR",
    "glEGLImageTargetTexture2DOES", "glEGLImageTargetRenderbufferStorageOES",
    "glEGLImageTargetTexStorageEXT", "glEGLImageTargetTextureStorageEXT",
}

ROW = re.compile(r'Signature \{ name: "(gl\w+)", ret: b\'(\w)\', params: "(\w*)", abi_ret: b\'(\w)\', abi: "(\w*)"')


def fnv1a64(data: bytes) -> int:
    h = 0xCBF29CE484222325
    for b in data:
        h ^= b
        h = (h * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return h


def commands():
    rows = []
    for line in open(TABLE, encoding="utf-8"):
        m = ROW.search(line)
        if m:
            rows.append((m.group(1), m.group(2), m.group(3)))
    if not rows:
        sys.exit(f"gen_gl_forward: no gl* commands in {TABLE}")
    # A command's id is its position, and eglGetProcAddress's table is searched by name: one order.
    if [r[0] for r in rows] != sorted(r[0] for r in rows):
        sys.exit("gen_gl_forward: the table's gl* commands are not sorted by name")
    return rows


def fingerprint(rows) -> int:
    return fnv1a64("".join(f"{n}:{p}:{r};" for n, r, p in rows).encode())


def c_param(cls: str, i: int) -> str:
    return {"I": f"uint64_t a{i}", "F": f"float a{i}", "D": f"double a{i}"}[cls]


def c_lane(cls: str, i: int) -> str:
    return {"I": f"a{i}", "F": f"omni_gl_f32(a{i})", "D": f"omni_gl_f64(a{i})"}[cls]


def main():
    rows = commands()
    out = []
    w = out.append
    w("/* @generated by tools/gen_gl_forward.py from crates/omni-android/src/gles/signatures.rs -- do not edit. */")
    w('#include "gl.h"')
    w("")
    w(f"const uint64_t omni_gl_fingerprint = 0x{fingerprint(rows):016x}ull;")
    w(f"const uint32_t omni_gl_command_count = {len(rows)};")
    w("")
    for i, (name, ret, params) in enumerate(rows):
        if name in SPECIAL:
            continue
        decl = ", ".join(c_param(c, j) for j, c in enumerate(params)) or "void"
        lanes = ", ".join(c_lane(c, j) for j, c in enumerate(params))
        argv = f"(const uint64_t[]){{{lanes}}}" if params else "NULL"
        call = f"omni_gl_call({i}u, {argv}, {len(params)}u)"
        rtype = {"V": "void", "I": "uint64_t", "F": "float"}[ret]
        w(f"OMNI_GL_EXPORT {rtype} {name}({decl}) {{")
        if ret == "V":
            w(f"    {call};")
        elif ret == "I":
            w(f"    return {call};")
        else:
            w(f"    return omni_gl_as_f32({call});")
        w("}")
    w("")
    w("/* Every command by name, in id order (which is name order), for eglGetProcAddress; the specials are gl_special.c's. */")
    for name in sorted(SPECIAL):
        w(f"extern void {name}(void);")
    w("const struct omni_gl_proc omni_gl_procs[] = {")
    for name, _, _ in rows:
        w(f'    {{"{name}", (void (*)(void)){name}}},')
    w("};")
    w(f"const uint32_t omni_gl_proc_count = {len(rows)};")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print(f"{OUT}: {len(rows)} commands ({len(rows) - len(SPECIAL & {r[0] for r in rows})} forwarded), fingerprint 0x{fingerprint(rows):016x}")


if __name__ == "__main__":
    main()
