"""Generate `crates/omni-android/src/gles/signatures.rs` from the Khronos registries.

    python3 tools/gen_gles_signatures.py <gl.xml> <egl.xml> > crates/omni-android/src/gles/signatures.rs

The GLES forwarder calls a host driver's function with the guest's arguments. Under identity
mapping the *values* need no translation, but the *calling convention* does: the guest passes
integer/pointer arguments in x0-x7 then the stack and floating-point ones in v0-v7 (AAPCS64), and
the host expects SysV (Linux, macOS x86-64) or the Microsoft x64 convention (Windows), where an
argument's register depends on its position among all arguments. So every command needs its exact
parameter classes, in order, and its return class. That list is the registry's, not ours: this
script reads it and emits it, and nothing in the table is typed by hand.

Classes: `I` -- an integer or pointer passed in a general register (every GL/EGL integer type,
enum, bitfield, handle, `GLsync`, `GLint64`, `GLfixed`, and every pointer); `F` -- `GLfloat` /
`GLclampf` passed by value (a 32-bit float register); `D` -- `GLdouble` / `GLclampd` by value.
Return: `V` void, `I` as above, `F` float.

Which commands: every command any `gles2` feature (`GL_ES_VERSION_2_0` .. `3_2`) or any extension
whose `supported` list names `gles2` requires, and every EGL command. Which of them a host really
has is the host's `eglGetProcAddress` answer at run time -- the table only says how to call one.
"""

import hashlib
import sys
import xml.etree.ElementTree as ET

FLOAT_TYPES = {"GLfloat", "GLclampf"}
DOUBLE_TYPES = {"GLdouble", "GLclampd"}


def param_class(elem):
    """The class of one <param> (or <proto>) element."""
    text = "".join(elem.itertext())
    ptype = elem.find("ptype")
    name = ptype.text if ptype is not None else None
    # Everything before the <name> child is the type; a '*' there makes it a pointer.
    type_text = text.rsplit(elem.find("name").text, 1)[0]
    if "*" in type_text:
        return "I"
    if name in FLOAT_TYPES:
        return "F"
    if name in DOUBLE_TYPES:
        return "D"
    if name is None:
        # A bare C type with no <ptype>: "void", "const void *" (pointer handled above)...
        stripped = type_text.replace("const", "").strip()
        if stripped == "void":
            return "V"
        if stripped in ("float",):
            return "F"
        if stripped in ("double",):
            return "D"
        return "I"
    return "I"


def commands(root):
    out = {}
    # The definitions live under <commands>; features and extensions only *reference* a command
    # by <command name="..."/>, and those references have no <proto>.
    for block in root.iter("commands"):
        for cmd in block.findall("command"):
            proto = cmd.find("proto")
            name = proto.find("name").text
            ret = param_class(proto)
            params = "".join(param_class(p) for p in cmd.findall("param"))
            out[name] = (ret, params)
    return out


def gles_names(root):
    names = {}
    for feature in root.iter("feature"):
        if feature.get("api") != "gles2":
            continue
        for req in feature.iter("require"):
            if req.get("api") not in (None, "gles2"):
                continue
            for c in req.iter("command"):
                names.setdefault(c.get("name"), feature.get("name"))
    for ext in root.iter("extension"):
        supported = (ext.get("supported") or "").split("|")
        if "gles2" not in supported:
            continue
        for req in ext.iter("require"):
            if req.get("api") not in (None, "gles2"):
                continue
            for c in req.iter("command"):
                names.setdefault(c.get("name"), ext.get("name"))
    return names


def main():
    gl_path, egl_path = sys.argv[1], sys.argv[2]
    gl_bytes, egl_bytes = open(gl_path, "rb").read(), open(egl_path, "rb").read()
    gl, egl = ET.fromstring(gl_bytes), ET.fromstring(egl_bytes)
    gl_cmds, egl_cmds = commands(gl), commands(egl)
    gles = gles_names(gl)
    rows = []
    for name in sorted(gles):
        ret, params = gl_cmds[name]
        rows.append((name, ret, params, gles[name]))
    for name in sorted(egl_cmds):
        ret, params = egl_cmds[name]
        rows.append((name, ret, params, "EGL"))
    w = sys.stdout.write
    w("// @generated by tools/gen_gles_signatures.py -- do not edit by hand.\n")
    w(f"// gl.xml  sha256 {hashlib.sha256(gl_bytes).hexdigest()} (KhronosGroup/OpenGL-Registry, Apache-2.0)\n")
    w(f"// egl.xml sha256 {hashlib.sha256(egl_bytes).hexdigest()} (KhronosGroup/EGL-Registry, Apache-2.0)\n")
    w("//! Every GLES (`gles2` API: ES 2.0-3.2 and its extensions) and EGL command's calling shape,\n")
    w("//! from the Khronos registries. See `tools/gen_gles_signatures.py` for the classes.\n\n")
    w("/// One command: its name, return class, parameter classes in order, and where the registry\n")
    w("/// defines it (a GLES version feature, an extension, or `EGL`).\n")
    w("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n")
    w("pub struct Signature {\n    /// The command's name.\n    pub name: &'static str,\n")
    w("    /// `V`, `I` or `F`.\n    pub ret: u8,\n")
    w("    /// One of `I`, `F`, `D` per parameter, in order.\n    pub params: &'static str,\n")
    w("    /// The feature or extension that requires it.\n    pub origin: &'static str,\n}\n\n")
    w(f"/// {len(rows)} commands, sorted by name within GLES then EGL.\n")
    w("pub static SIGNATURES: &[Signature] = &[\n")
    for name, ret, params, origin in rows:
        w(f"    Signature {{ name: \"{name}\", ret: b'{ret}', params: \"{params}\", origin: \"{origin}\" }},\n")
    w("];\n")


if __name__ == "__main__":
    main()
