#!/usr/bin/env python3
"""Generate Rust from frozen AIDL API files: python tools/gen_aidl.py [--check].

Input: the normalized frozen API snapshots (`aidl_api/<package>/<version>/`) vendored under
`tools/aidl/<package>/<version>/` (see each `SOURCE.txt`), with each version's `.hash`.
Output: `crates/omni-linux/src/hal/aidl/mod.rs` and one module per package, e.g.
`android_hardware_graphics_composer3.rs`:

- every parcelable as a struct, every union as an enum, every AIDL enum as a newtype with
  associated consts, each with exact wire (de)serialization in the NDK backend's format
  (`crates/omni-linux/src/hal/parcel.rs` documents the wire);
- every interface as a module with its descriptor, version, hash, constants and transaction codes,
  a server trait (`<I>Server`) and its dispatcher (`dispatch`), and a client proxy (`<I>Proxy`)
  with an `encode_<method>`/`decode_<method>` pair per method.

The runtime they share (`Ctx`, `Status`, `Fd`, `Binder`, `CallError`, ...) is hand-written in
`hal/aidl/runtime.rs`. The output is deterministic; `--check` fails when it is not up to date.
Standard library only.
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
AIDL_ROOT = os.path.join(HERE, "aidl")
OUT_DIR = os.path.join(REPO, "crates", "omni-linux", "src", "hal", "aidl")

# Android 15: composer3 V3 imports graphics.common V5 and hardware.common V2 (its Android.bp).
PACKAGES = [
    ("android.hardware.graphics.composer3", "3"),
    ("android.hardware.graphics.common", "5"),
    ("android.hardware.common", "2"),
]

HEADER = "// generated by tools/gen_aidl.py -- do not edit\n"

FILE_ALLOWS = (
    "#![allow(\n"
    "    non_camel_case_types,\n"
    "    non_upper_case_globals,\n"
    "    dead_code,\n"
    "    unused_imports,\n"
    "    unused_variables,\n"
    "    unused_parens,\n"
    "    clippy::all,\n"
    "    clippy::pedantic\n"
    ")]\n"
)


class GenError(Exception):
    pass


# ---------------------------------------------------------------------------------------------
# Lexing

TOKEN_RE = re.compile(
    r"""
     (?P<ws>\s+)
    |(?P<lc>//[^\n]*)
    |(?P<bc>/\*.*?\*/)
    |(?P<float>(?:\d+\.\d*|\.\d+)(?:[eE][+-]?\d+)?[fFdD]?|\d+[eE][+-]?\d+[fFdD]?|\d+[fF](?![0-9A-Za-z_]))
    |(?P<int>0[xX][0-9a-fA-F]+[lL]?|\d+[lL]?)
    |(?P<str>"(?:\\.|[^"\\])*")
    |(?P<char>'(?:\\.|[^'\\])')
    |(?P<id>[A-Za-z_][A-Za-z0-9_]*)
    |(?P<op><<|>>|<=|>=|==|!=|&&|\|\||[{}()\[\]<>;,=.@?:+\-*/%&|^~!])
    """,
    re.S | re.X,
)


class Tok:
    __slots__ = ("kind", "text", "where")

    def __init__(self, kind, text, where):
        self.kind, self.text, self.where = kind, text, where

    def __repr__(self):
        return "Tok(%s,%r)" % (self.kind, self.text)


def lex(src, path):
    toks, pos, line = [], 0, 1
    while pos < len(src):
        m = TOKEN_RE.match(src, pos)
        if not m:
            raise GenError("%s:%d: cannot read %r" % (path, line, src[pos:pos + 20]))
        kind = m.lastgroup
        text = m.group(kind)
        if kind not in ("ws", "lc", "bc"):
            toks.append(Tok(kind, text, "%s:%d" % (path, line)))
        line += text.count("\n")
        pos = m.end()
    toks.append(Tok("eof", "", "%s:%d" % (path, line)))
    return toks


# ---------------------------------------------------------------------------------------------
# The parsed model

DECL_KEYWORDS = ("parcelable", "union", "enum", "interface")


class TypeRef:
    def __init__(self, name, args, dims, ann, where):
        self.name, self.args, self.dims, self.ann, self.where = name, args, dims, ann, where


class Field:
    def __init__(self, name, type_ref, default, where):
        self.name, self.type, self.default, self.where = name, type_ref, default, where


class Const:
    def __init__(self, name, type_ref, expr, where):
        self.name, self.type, self.expr, self.where = name, type_ref, expr, where


class Param:
    def __init__(self, direction, type_ref, name):
        self.direction, self.type, self.name = direction, type_ref, name


class Method:
    def __init__(self, name, ret, params, oneway, code, where):
        self.name, self.ret, self.params, self.oneway, self.code, self.where = name, ret, params, oneway, code, where


class Decl:
    def __init__(self, kind, name, pkg, outer, ann, where):
        self.kind, self.name, self.pkg, self.outer, self.ann, self.where = kind, name, pkg, outer, ann, where
        self.fields, self.consts, self.nested, self.enumerators, self.methods = [], [], [], [], []
        self.oneway = False
        self.imports = []

    @property
    def path(self):
        return (self.outer.path if self.outer else []) + [self.name]

    @property
    def fq(self):
        return self.pkg + "." + ".".join(self.path)

    def all(self):
        yield self
        for n in self.nested:
            yield from n.all()


# ---------------------------------------------------------------------------------------------
# Parsing


class Parser:
    def __init__(self, toks):
        self.t, self.i = toks, 0

    def peek(self, k=0):
        return self.t[min(self.i + k, len(self.t) - 1)]

    def next(self):
        tok = self.peek()
        if tok.kind == "eof":
            self.fail("unexpected end of file")
        self.i += 1
        return tok

    def at(self, text, k=0):
        tok = self.peek(k)
        return tok.kind in ("op", "id") and tok.text == text

    def accept(self, text):
        if self.at(text):
            self.i += 1
            return True
        return False

    def expect(self, text):
        if not self.accept(text):
            self.fail("expected %r" % text)

    def fail(self, msg):
        tok = self.peek()
        raise GenError("%s: %s, found %r" % (tok.where, msg, tok.text))

    def ident(self):
        tok = self.peek()
        if tok.kind != "id":
            self.fail("expected a name")
        self.i += 1
        return tok.text

    def qname(self):
        parts = [self.ident()]
        while self.at(".") and self.peek(1).kind == "id":
            self.i += 1
            parts.append(self.ident())
        return ".".join(parts)

    def annotations(self):
        ann = {}
        while self.at("@"):
            self.i += 1
            name = self.qname()
            args = []
            if self.at("("):
                depth = 0
                while True:
                    tok = self.next()
                    if tok.kind == "op" and tok.text == "(":
                        depth += 1
                    elif tok.kind == "op" and tok.text == ")":
                        depth -= 1
                    args.append(tok.text)
                    if depth == 0:
                        break
                args = args[1:-1]
            ann[name] = " ".join(args)
        return ann

    def expr_until(self, stops):
        out, depth = [], 0
        while True:
            tok = self.peek()
            if tok.kind == "eof":
                self.fail("an unterminated expression")
            if depth == 0 and tok.kind == "op" and tok.text in stops:
                break
            if tok.kind == "op" and tok.text in ("(", "{", "["):
                depth += 1
            elif tok.kind == "op" and tok.text in (")", "}", "]"):
                depth -= 1
            out.append(tok)
            self.i += 1
        if not out:
            self.fail("expected an expression")
        return out

    def close_angle(self):
        tok = self.peek()
        if tok.kind == "op" and tok.text == ">":
            self.i += 1
        elif tok.kind == "op" and tok.text == ">>":
            tok.text = ">"  # the first of the two closes this list; the other stays
        else:
            self.fail("expected '>'")

    def type_ref(self):
        ann = self.annotations()
        where = self.peek().where
        name = self.qname()
        args = []
        if self.accept("<"):
            while True:
                args.append(self.type_ref())
                if self.accept(","):
                    continue
                self.close_angle()
                break
        dims = []
        while self.accept("["):
            if self.accept("]"):
                dims.append(None)
            else:
                dims.append(self.expr_until({"]"}))
                self.expect("]")
        return TypeRef(name, args, dims, ann, where)

    def file(self):
        self.expect("package")
        pkg = self.qname()
        self.expect(";")
        imports = []
        while self.accept("import"):
            imports.append(self.qname())
            self.expect(";")
        decls = []
        while self.peek().kind != "eof":
            decls.append(self.decl(pkg, None))
        return pkg, imports, decls

    def decl(self, pkg, outer):
        ann = self.annotations()
        oneway = self.accept("oneway")
        ann.update(self.annotations())
        where = self.peek().where
        kw = self.ident()
        if kw not in DECL_KEYWORDS:
            raise GenError("%s: expected a declaration, found %r" % (where, kw))
        name = self.ident()
        d = Decl(kw, name, pkg, outer, ann, where)
        d.oneway = oneway
        if self.at("<"):
            raise GenError("%s: generic parcelable %s is not supported" % (where, name))
        if self.at(";") or self.at("cpp_header") or self.at("ndk_header") or self.at("rust_type"):
            raise GenError("%s: unstructured parcelable %s is not supported" % (where, name))
        self.expect("{")
        if kw == "enum":
            self.enum_body(d)
        else:
            while not self.accept("}"):
                self.member(d)
        return d

    def enum_body(self, d):
        while not self.accept("}"):
            self.annotations()
            where = self.peek().where
            name = self.ident()
            expr = self.expr_until({",", "}"}) if self.accept("=") else None
            d.enumerators.append((name, expr, where))
            if not self.accept(","):
                self.expect("}")
                break

    def member(self, d):
        start = self.i
        ann = self.annotations()
        if (self.peek().kind == "id" and self.peek().text in DECL_KEYWORDS) or (self.at("oneway") and self.at("interface", 1)):
            self.i = start
            n = self.decl(d.pkg, d)
            d.nested.append(n)
            return
        where = self.peek().where
        if self.accept("const"):
            t = self.type_ref()
            name = self.ident()
            self.expect("=")
            expr = self.expr_until({";"})
            self.expect(";")
            d.consts.append(Const(name, t, expr, where))
            return
        if d.kind == "interface":
            oneway = self.accept("oneway")
            ret = self.type_ref()
            ret.ann.update(ann)
            name = self.ident()
            self.expect("(")
            params = []
            if not self.accept(")"):
                while True:
                    pann = self.annotations()
                    direction = "in"
                    if self.peek().kind == "id" and self.peek().text in ("in", "out", "inout"):
                        direction = self.next().text
                    t = self.type_ref()
                    t.ann.update(pann)
                    params.append(Param(direction, t, self.ident()))
                    if self.accept(")"):
                        break
                    self.expect(",")
            code = None
            if self.accept("="):
                toks = self.expr_until({";"})
                if len(toks) != 1 or toks[0].kind != "int":
                    raise GenError("%s: a transaction id must be an integer" % where)
                code = int(toks[0].text.rstrip("lL"), 0)
            self.expect(";")
            d.methods.append(Method(name, ret, params, oneway or d.oneway, code, where))
            return
        t = self.type_ref()
        t.ann.update(ann)
        name = self.ident()
        default = self.expr_until({";"}) if self.accept("=") else None
        self.expect(";")
        d.fields.append(Field(name, t, default, where))


# ---------------------------------------------------------------------------------------------
# Resolved types

PRIMS = {
    # AIDL type: (Rust type, Reader/Writer method, bits for integers)
    "boolean": ("bool", "bool", None),
    "byte": ("i8", "i8", 8),
    "char": ("u16", "char16", None),
    "int": ("i32", "i32", 32),
    "long": ("i64", "i64", 64),
    "float": ("f32", "f32", None),
    "double": ("f64", "f64", None),
}
PRIM_ARRAYS = {"boolean": "bool_array", "char": "char16_array", "int": "i32_array", "long": "i64_array", "float": "f32_array", "double": "f64_array"}
BACKINGS = {"byte": ("i8", 8), "int": ("i32", 32), "long": ("i64", 64)}
UNSUPPORTED_TYPES = {
    "ParcelableHolder": "ParcelableHolder",
    "Map": "Map",
    "FileDescriptor": "FileDescriptor (a raw file descriptor)",
    "CharSequence": "CharSequence",
}


class T:
    """A resolved type: kind is prim, string, pfd, binder, enum, parcelable, union, interface,
    array or void."""

    def __init__(self, kind, nullable=False, prim=None, decl=None, elem=None, fixed=None):
        self.kind, self.nullable, self.prim, self.decl, self.elem, self.fixed = kind, nullable, prim, decl, elem, fixed

    def copy(self):
        return T(self.kind, self.nullable, self.prim, self.decl, self.elem, self.fixed)

    def is_copy(self):
        return self.kind in ("prim", "enum", "binder", "interface")


RUST_KEYWORDS = set(
    "as break const continue crate else enum extern false fn for if impl in let loop match mod move mut pub ref "
    "return self Self static struct super trait true type unsafe use where while async await dyn abstract become "
    "box do final macro override priv typeof unsized virtual yield try gen".split()
)
# Names the generated code uses unqualified; an AIDL type may not take one.
RESERVED_TYPE_NAMES = {"Arc", "Broker", "HostCall", "HostReply", "Malformed", "Reader", "Writer", "Ctx", "Status", "Fd", "Binder", "CallError", "Option", "Vec", "String", "Result", "Self"}
# Local names in generated functions; an AIDL parameter of one of these names gets a `_` suffix.
RESERVED_LOCALS = {"r", "w", "out", "reply", "offsets", "svc", "ctx", "call", "ret", "end", "at"}


def snake(name):
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    return s.lower()


def ident(name):
    """A Rust identifier for an AIDL name already in the right case."""
    if name in ("self", "Self", "super", "crate"):
        return name + "_"
    if name in RUST_KEYWORDS:
        return "r#" + name
    return name


def field_ident(name):
    return ident(snake(name))


def local_ident(name):
    s = snake(name)
    if s in RESERVED_LOCALS:
        s += "_"
    return ident(s)


def variant_ident(name):
    return name[:1].upper() + name[1:]


def rust_name(decl):
    return "_".join(decl.path)


def module_name(pkg):
    return pkg.replace(".", "_")


# ---------------------------------------------------------------------------------------------
# The model: every declaration of every package, and name resolution


class Package:
    def __init__(self, name, version, hash_, decls, root):
        self.name, self.version, self.hash, self.decls, self.root = name, version, hash_, decls, root


class Model:
    def __init__(self):
        self.packages = []
        self.decls = {}
        self.errors = []
        self._values = {}
        self._defaultable = {}

    def load(self, aidl_root, pkg, version):
        root = os.path.join(aidl_root, pkg, version)
        if not os.path.isdir(root):
            raise GenError("%s: no frozen API directory" % root)
        hash_path = os.path.join(root, ".hash")
        with open(hash_path, encoding="utf-8") as f:
            hashes = [l.strip() for l in f.read().splitlines() if l.strip()]
        if not hashes:
            raise GenError("%s: empty" % hash_path)
        files = []
        for dirpath, _, names in os.walk(root):
            for n in names:
                if n.endswith(".aidl"):
                    files.append(os.path.join(dirpath, n))
        files.sort(key=lambda p: os.path.relpath(p, root).replace(os.sep, "/"))
        decls = []
        for path in files:
            rel = os.path.relpath(path, aidl_root).replace(os.sep, "/")
            with open(path, encoding="utf-8") as f:
                src = f.read()
            file_pkg, imports, file_decls = Parser(lex(src, rel)).file()
            if file_pkg != pkg:
                raise GenError("%s: package %s in %s's directory" % (rel, file_pkg, pkg))
            for d in file_decls:
                for x in d.all():
                    x.imports = imports
                    if x.fq in self.decls:
                        raise GenError("%s: %s declared twice" % (x.where, x.fq))
                    if rust_name(x) in RESERVED_TYPE_NAMES:
                        raise GenError("%s: the type name %s is reserved by the generated code" % (x.where, rust_name(x)))
                    self.decls[x.fq] = x
                decls.append(d)
        # The last hash is the one the frozen build compiles in.
        self.packages.append(Package(pkg, int(version), hashes[-1], decls, root))

    def lookup(self, name, scope):
        if name in self.decls:
            return self.decls[name]
        s = scope
        while s is not None:
            cand = s.fq + "." + name
            if cand in self.decls:
                return self.decls[cand]
            s = s.outer
        cand = scope.pkg + "." + name
        if cand in self.decls:
            return self.decls[cand]
        first = name.split(".")[0]
        for imp in scope.imports:
            if imp.split(".")[-1] == first:
                cand = imp + name[len(first):]
                if cand in self.decls:
                    return self.decls[cand]
        return None

    def resolve(self, tr, scope):
        nullable = "nullable" in tr.ann
        if tr.dims:
            inner = TypeRef(tr.name, tr.args, tr.dims[1:], {k: v for k, v in tr.ann.items() if k != "nullable"}, tr.where)
            elem = self.resolve(inner, scope)
            fixed = None
            if tr.dims[0] is not None:
                fixed = self.eval(tr.dims[0], scope)[0]
                if not isinstance(fixed, int) or fixed < 0:
                    raise GenError("%s: a fixed array size must be a non-negative integer" % tr.where)
            return self.array(elem, nullable, fixed)
        name = tr.name
        if name in UNSUPPORTED_TYPES:
            raise GenError("%s: %s is not supported" % (tr.where, UNSUPPORTED_TYPES[name]))
        if name == "List":
            if len(tr.args) != 1:
                raise GenError("%s: List takes one type" % tr.where)
            return self.array(self.resolve(tr.args[0], scope), nullable, None)
        if tr.args:
            raise GenError("%s: %s takes no type arguments" % (tr.where, name))
        if name in PRIMS:
            if nullable:
                raise GenError("%s: a @nullable %s" % (tr.where, name))
            return T("prim", prim=name)
        if name == "void":
            return T("void")
        if name == "String":
            return T("string", nullable)
        if name == "ParcelFileDescriptor":
            return T("pfd", nullable)
        if name == "IBinder":
            return T("binder", nullable)
        decl = self.lookup(name, scope)
        if decl is None:
            raise GenError("%s: unknown type %s" % (tr.where, name))
        if decl.kind == "enum" and nullable:
            raise GenError("%s: a @nullable enum" % tr.where)
        return T(decl.kind, nullable, decl=decl)

    @staticmethod
    def array(elem, nullable, fixed):
        if elem.kind == "void":
            raise GenError("an array of void")
        if nullable and elem.kind in ("string", "pfd", "parcelable", "union"):
            # The NDK's @nullable T[]: std::optional<std::vector<std::optional<T>>>.
            elem = elem.copy()
            elem.nullable = True
        return T("array", nullable, elem=elem, fixed=fixed)

    # -- constant expressions ------------------------------------------------------------------

    def value_of(self, decl, name, where):
        key = (decl.fq, name)
        if key in self._values:
            v = self._values[key]
            if v is None:
                raise GenError("%s: %s.%s refers to itself" % (where, decl.fq, name))
            return v
        self._values[key] = None
        if decl.kind == "enum":
            names = [e[0] for e in decl.enumerators]
            if name not in names:
                raise GenError("%s: %s has no %s" % (where, decl.fq, name))
            i = names.index(name)
            _, expr, ewhere = decl.enumerators[i]
            if expr is not None:
                v = self.eval(expr, decl)[0]
            elif i == 0:
                v = 0
            else:
                v = self.value_of(decl, names[i - 1], ewhere) + 1
            if isinstance(v, bool):
                v = int(v)
            if not isinstance(v, int):
                raise GenError("%s: %s.%s is not an integer" % (ewhere, decl.fq, name))
            v = wrap(v, BACKINGS[backing(decl)][1])
        else:
            c = next((c for c in decl.consts if c.name == name), None)
            if c is None:
                raise GenError("%s: %s has no constant %s" % (where, decl.fq, name))
            v = self.const_value(c, decl)
        self._values[key] = v
        return v

    def const_value(self, c, decl):
        t = self.resolve(c.type, decl)
        v = self.eval(c.expr, decl)[0]
        return coerce(v, t, c.where)

    def eval(self, toks, scope):
        """(value, reference): the value of a constant expression, and the (enum decl, name) it
        is when it is only a reference to an enumerator."""
        ev = Evaluator(self, toks, scope)
        v = ev.expr(0)
        if ev.i != len(toks):
            raise GenError("%s: cannot read the expression after %r" % (toks[ev.i].where, toks[ev.i].text))
        ref = None
        if all(t.kind == "id" or t.text == "." for t in toks):
            ref = ev.last_ref
        return v, ref

    def resolve_name(self, dotted, scope, where):
        parts = dotted.split(".")
        if len(parts) == 1:
            s = scope
            while s is not None:
                if s.kind == "enum" and any(e[0] == dotted for e in s.enumerators):
                    return self.value_of(s, dotted, where), (s, dotted)
                if any(c.name == dotted for c in s.consts):
                    return self.value_of(s, dotted, where), None
                s = s.outer
            raise GenError("%s: unknown name %s" % (where, dotted))
        type_name, member = ".".join(parts[:-1]), parts[-1]
        decl = self.lookup(type_name, scope)
        if decl is None:
            raise GenError("%s: unknown type %s" % (where, type_name))
        v = self.value_of(decl, member, where)
        return v, ((decl, member) if decl.kind == "enum" else None)

    # -- what can default -----------------------------------------------------------------------

    def t_defaultable(self, t):
        if t.nullable:
            return True
        if t.kind == "array":
            return t.fixed is None or self.t_defaultable(t.elem)
        if t.kind == "pfd":
            return False
        if t.kind in ("parcelable", "union"):
            return self.defaultable(t.decl)
        return True

    def defaultable(self, d):
        if d.fq in self._defaultable:
            v = self._defaultable[d.fq]
            return True if v is None else v
        self._defaultable[d.fq] = None
        if d.kind == "parcelable":
            v = all(f.default is not None or self.t_defaultable(self.resolve(f.type, d)) for f in d.fields)
        elif d.kind == "union":
            f = d.fields[0]
            v = f.default is not None or self.t_defaultable(self.resolve(f.type, d))
        else:
            v = True
        self._defaultable[d.fq] = v
        return v


def backing(decl):
    b = decl.ann.get("Backing")
    if b is None:
        return "byte"  # AIDL's default backing type
    m = re.search(r'type\s*=\s*"(\w+)"', b)
    if not m or m.group(1) not in BACKINGS:
        raise GenError("%s: unsupported @Backing(%s)" % (decl.where, b))
    return m.group(1)


def wrap(v, bits):
    v &= (1 << bits) - 1
    if v >= 1 << (bits - 1):
        v -= 1 << bits
    return v


def coerce(v, t, where):
    """A constant's value as a value of type t."""
    if t.kind == "prim":
        if t.prim == "boolean":
            return bool(v)
        if t.prim in ("float", "double"):
            if isinstance(v, (bool, int, float)):
                return float(v)
            raise GenError("%s: not a number" % where)
        if t.prim == "char":
            if isinstance(v, str) and len(v) == 1:
                return ord(v)
            if isinstance(v, int):
                return v & 0xFFFF
            raise GenError("%s: not a char" % where)
        if isinstance(v, bool):
            v = int(v)
        if not isinstance(v, int):
            raise GenError("%s: not an integer" % where)
        return wrap(v, PRIMS[t.prim][2])
    if t.kind == "string":
        if not isinstance(v, str):
            raise GenError("%s: not a string" % where)
        return v
    if t.kind == "enum":
        if isinstance(v, bool):
            v = int(v)
        return wrap(v, BACKINGS[backing(t.decl)][1])
    raise GenError("%s: a constant of this type is not supported" % where)


BINARY = {"||": 1, "&&": 2, "|": 3, "^": 4, "&": 5, "==": 6, "!=": 6, "<": 7, ">": 7, "<=": 7, ">=": 7, "<<": 8, ">>": 8, "+": 9, "-": 9, "*": 10, "/": 10, "%": 10}


def c_div(a, b):
    q = abs(a) // abs(b)
    return q if (a >= 0) == (b >= 0) else -q


def unescape(body):
    return bytes(body, "utf-8").decode("unicode_escape")


class Evaluator:
    def __init__(self, model, toks, scope):
        self.m, self.toks, self.scope, self.i = model, toks, scope, 0
        self.last_ref = None

    def peek(self):
        return self.toks[self.i] if self.i < len(self.toks) else None

    def where(self):
        tok = self.peek() or self.toks[-1]
        return tok.where

    def take(self, text=None):
        tok = self.peek()
        if tok is None or (text is not None and tok.text != text):
            raise GenError("%s: expected %r in a constant expression" % (self.where(), text or "more"))
        self.i += 1
        return tok

    def expr(self, min_prec):
        left = self.unary()
        while True:
            tok = self.peek()
            if tok is None or tok.kind != "op":
                return left
            if tok.text == "?" and min_prec == 0:
                self.i += 1
                a = self.expr(0)
                self.take(":")
                b = self.expr(0)
                left = a if left else b
                continue
            prec = BINARY.get(tok.text)
            if prec is None or prec < min_prec:
                return left
            self.i += 1
            right = self.expr(prec + 1)
            left = self.binary(tok, left, right)

    def binary(self, tok, a, b):
        op = tok.text
        if op == "+" and isinstance(a, str) and isinstance(b, str):
            return a + b
        if op in ("||", "&&"):
            return bool(a) or bool(b) if op == "||" else bool(a) and bool(b)
        if op in ("==", "!=", "<", ">", "<=", ">="):
            return {"==": a == b, "!=": a != b, "<": a < b, ">": a > b, "<=": a <= b, ">=": a >= b}[op]
        if isinstance(a, bool):
            a = int(a)
        if isinstance(b, bool):
            b = int(b)
        if isinstance(a, float) or isinstance(b, float):
            if op in ("+", "-", "*", "/"):
                return {"+": a + b, "-": a - b, "*": a * b, "/": a / b}[op]
            raise GenError("%s: %s of a float" % (tok.where, op))
        if not isinstance(a, int) or not isinstance(b, int):
            raise GenError("%s: %s of a non-number" % (tok.where, op))
        if op in ("/", "%") and b == 0:
            raise GenError("%s: division by zero" % tok.where)
        return {
            "|": lambda: a | b, "^": lambda: a ^ b, "&": lambda: a & b,
            "<<": lambda: a << b, ">>": lambda: a >> b, "+": lambda: a + b, "-": lambda: a - b,
            "*": lambda: a * b, "/": lambda: c_div(a, b), "%": lambda: a - c_div(a, b) * b,
        }[op]()

    def unary(self):
        tok = self.take()
        if tok.kind == "op" and tok.text in ("-", "+", "~", "!"):
            v = self.unary()
            if isinstance(v, bool) and tok.text != "!":
                v = int(v)
            return {"-": lambda: -v, "+": lambda: v, "~": lambda: ~v, "!": lambda: not v}[tok.text]()
        if tok.kind == "op" and tok.text == "(":
            v = self.expr(0)
            self.take(")")
            return v
        if tok.kind == "op" and tok.text == "{":
            items = []
            if self.peek() is not None and self.peek().text == "}":
                self.i += 1
                return items
            while True:
                items.append(self.expr(0))
                t = self.take()
                if t.text == "}":
                    return items
                if t.text != ",":
                    raise GenError("%s: expected ',' or '}'" % t.where)
                if self.peek() is not None and self.peek().text == "}":
                    self.i += 1
                    return items
        if tok.kind == "int":
            return int(tok.text.rstrip("lL"), 0)
        if tok.kind == "float":
            return float(tok.text.rstrip("fFdD"))
        if tok.kind == "str":
            return unescape(tok.text[1:-1])
        if tok.kind == "char":
            return unescape(tok.text[1:-1])
        if tok.kind == "id":
            if tok.text == "true":
                return True
            if tok.text == "false":
                return False
            if tok.text == "null":
                return None
            parts = [tok.text]
            while self.peek() is not None and self.peek().text == "." and self.i + 1 < len(self.toks) and self.toks[self.i + 1].kind == "id":
                self.i += 1
                parts.append(self.take().text)
            v, ref = self.m.resolve_name(".".join(parts), self.scope, tok.where)
            self.last_ref = ref
            return v
        raise GenError("%s: unexpected %r in a constant expression" % (tok.where, tok.text))


# ---------------------------------------------------------------------------------------------
# Rust emission


def rfloat(v):
    s = repr(float(v))
    if s in ("inf", "-inf", "nan"):
        raise GenError("a non-finite float constant")
    if "." not in s and "e" not in s:
        s += ".0"
    return s


def rstr(s):
    out = []
    for ch in s:
        if ch in ('"', "\\"):
            out.append("\\" + ch)
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append("\\u{%x}" % ord(ch))
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def indent(lines, n=1):
    pad = "    " * n
    return [pad + l if l else l for l in lines]


class Emitter:
    def __init__(self, model, package):
        self.m, self.pkg = model, package
        self.counter = 0

    def fresh(self, base):
        self.counter += 1
        return "%s%d" % (base, self.counter)

    def path(self, decl):
        name = rust_name(decl)
        if decl.pkg == self.pkg.name:
            return name
        return "%s::%s" % (module_name(decl.pkg), name)

    def rty(self, t):
        k = t.kind
        if k == "void":
            return "()"
        if k == "array":
            if t.elem.kind == "prim" and t.elem.prim == "byte":
                inner = "Vec<u8>"
            else:
                inner = "Vec<%s>" % self.rty(t.elem)
            return "Option<%s>" % inner if t.nullable else inner
        if k in ("binder", "interface"):
            return "Binder"
        if k == "prim":
            base = PRIMS[t.prim][0]
        elif k == "string":
            base = "String"
        elif k == "pfd":
            base = "Fd"
        else:
            base = self.path(t.decl)
        return "Option<%s>" % base if t.nullable else base

    @staticmethod
    def stability(scope):
        s = scope
        while s is not None:
            if "VintfStability" in s.ann:
                return "crate::binder::STABILITY_VINTF"
            s = s.outer
        return "crate::binder::STABILITY_SYSTEM"

    # -- reading and writing one value ----------------------------------------------------------

    def rd(self, t):
        """A Rust expression reading a value of type t from `r` (a `&mut Reader`)."""
        k = t.kind
        if k == "prim":
            return "r.%s()?" % PRIMS[t.prim][1]
        if k == "string":
            return "r.string16()?" if t.nullable else 'r.string16()?.ok_or(Malformed("a null string"))?'
        if k == "pfd":
            return "Fd::read_nullable(r)?" if t.nullable else "Fd::read(r)?"
        if k in ("binder", "interface"):
            return "Binder::read(r)?" if t.nullable else "Binder::read_required(r)?"
        if k == "enum":
            return "%s::read(r)?" % self.path(t.decl)
        if k in ("parcelable", "union"):
            return "%s::%s(r)?" % (self.path(t.decl), "read_nullable" if t.nullable else "read_value")
        if k == "array":
            e = t.elem
            if e.kind == "prim" and e.prim == "byte":
                opt = "r.byte_array()?.map(<[u8]>::to_vec)"
            elif e.kind == "enum" and backing(e.decl) == "byte":
                opt = "r.byte_array()?.map(|b| b.iter().map(|&x| %s(x as i8)).collect::<Vec<_>>())" % self.path(e.decl)
            elif e.kind == "prim":
                opt = "r.%s()?" % PRIM_ARRAYS[e.prim]
            elif e.kind == "enum":
                method = "i64_array" if backing(e.decl) == "long" else "i32_array"
                opt = "r.%s()?.map(|v| v.into_iter().map(%s).collect::<Vec<_>>())" % (method, self.path(e.decl))
            else:
                opt = "read_vec(r, |r| Ok(%s))?" % self.rd(e)
            if t.fixed is not None:
                opt = "fixed_len(%s, %d)?" % (opt, t.fixed)
            return opt if t.nullable else '%s.ok_or(Malformed("a null array"))?' % opt
        raise GenError("cannot read a %s" % k)

    def wr(self, t, p, scope):
        """Statements writing the value at place p (of type t) to `w` (a `&mut Writer`)."""
        k = t.kind
        if k == "prim":
            return ["w.%s(%s);" % (PRIMS[t.prim][1], p)]
        if k == "string":
            if t.nullable:
                s = self.fresh("s")
                return ["match &%s {" % p, "    Some(%s) => w.string16(%s)," % (s, s), "    None => w.null(),", "}"]
            return ["w.string16(&%s);" % p]
        if k == "pfd":
            return ["Fd::write_nullable(%s.as_ref(), w);" % p] if t.nullable else ["%s.write(w);" % p]
        if k in ("binder", "interface"):
            return ["%s.write(w, %s);" % (p, self.stability(t.decl if k == "interface" else scope))]
        if k == "enum":
            return ["%s.write(w);" % p]
        if k in ("parcelable", "union"):
            if t.nullable:
                return ["%s::write_nullable(%s.as_ref(), w);" % (self.path(t.decl), p)]
            return ["%s.write_value(w);" % p]
        if k == "array":
            e = t.elem

            def body(q):
                if e.kind == "prim" and e.prim == "byte":
                    return ["w.byte_array(&%s);" % q]
                if e.kind == "enum" and backing(e.decl) == "byte":
                    return ["w.byte_array(&%s.iter().map(|x| x.0 as u8).collect::<Vec<u8>>());" % q]
                if e.kind == "prim":
                    return ["w.%s(&%s);" % (PRIM_ARRAYS[e.prim], q)]
                if e.kind == "enum":
                    method = "i64_array" if backing(e.decl) == "long" else "i32_array"
                    return ["w.%s(&%s.iter().map(|x| x.0).collect::<Vec<_>>());" % (method, q)]
                x = self.fresh("x")
                return ["w.i32(%s.len() as i32);" % q, "for %s in %s.iter() {" % (x, q)] + indent(self.wr(e, "(*%s)" % x, scope)) + ["}"]

            if t.nullable:
                v = self.fresh("v")
                return ["match &%s {" % p, "    Some(%s) => {" % v] + indent(body("(*%s)" % v), 2) + ["    }", "    None => w.null(),", "}"]
            return body(p)
        raise GenError("cannot write a %s" % k)

    # -- default values -------------------------------------------------------------------------

    def default_expr(self, t, expr, scope, where):
        if expr is None:
            if t.nullable:
                return "None"
            if t.kind == "array" and t.fixed is not None:
                return "vec![Default::default(); %d]" % t.fixed
            return "Default::default()"
        v, ref = self.m.eval(expr, scope)
        if v is None:
            if not t.nullable:
                raise GenError("%s: null for a non-null value" % where)
            return "None"
        s = self.value_expr(t, v, ref, where)
        return "Some(%s)" % s if t.nullable else s

    def value_expr(self, t, v, ref, where):
        k = t.kind
        if k == "prim":
            c = coerce(v, t, where)
            if t.prim == "boolean":
                return "true" if c else "false"
            if t.prim in ("float", "double"):
                return rfloat(c)
            return str(c)
        if k == "string":
            return "String::from(%s)" % rstr(coerce(v, t, where))
        if k == "enum":
            if ref is not None and ref[0] is t.decl:
                return "%s::%s" % (self.path(t.decl), ref[1])
            return "%s(%d)" % (self.path(t.decl), coerce(v, t, where))
        if k == "array":
            if not isinstance(v, list):
                raise GenError("%s: an array default that is not a list" % where)
            e = t.elem
            items = [self.value_expr(e, x, None, where) for x in v]
            if e.kind == "prim" and e.prim == "byte":
                items = ["%s_u8" % (x if not x.startswith("-") else str(int(x) & 0xFF)) for x in items]
            return "vec![%s]" % ", ".join(items)
        raise GenError("%s: a default value of this type is not supported" % where)

    # -- declarations ---------------------------------------------------------------------------

    def consts_block(self, d):
        out = []
        for c in d.consts:
            t = self.m.resolve(c.type, d)
            v = self.m.const_value(c, d)
            if t.kind == "string":
                out.append("pub const %s: &str = %s;" % (ident(c.name), rstr(v)))
            elif t.kind == "prim":
                out.append("pub const %s: %s = %s;" % (ident(c.name), PRIMS[t.prim][0], self.value_expr(t, v, None, c.where)))
            else:
                raise GenError("%s: a constant of type %s is not supported" % (c.where, c.type.name))
        return out

    def value_helpers(self, name):
        return [
            "",
            "/// The value anywhere else a %s is: its non-null marker, then [`Self::read`]." % name,
            "pub fn read_value(r: &mut Reader<'_>) -> Result<Self, Malformed> {",
            "    if !r.marker()? {",
            '        return Err(Malformed("a null %s"));' % name,
            "    }",
            "    Self::read(r)",
            "}",
            "",
            "/// A `@nullable` value: its marker (0 for null), then [`Self::read`].",
            "pub fn read_nullable(r: &mut Reader<'_>) -> Result<Option<Self>, Malformed> {",
            "    if r.marker()? {",
            "        Ok(Some(Self::read(r)?))",
            "    } else {",
            "        Ok(None)",
            "    }",
            "}",
            "",
            "pub fn write_value(&self, w: &mut Writer) {",
            "    w.marker(true);",
            "    self.write(w);",
            "}",
            "",
            "pub fn write_nullable(v: Option<&Self>, w: &mut Writer) {",
            "    match v {",
            "        Some(v) => v.write_value(w),",
            "        None => w.marker(false),",
            "    }",
            "}",
        ]

    def emit_enum(self, d):
        name = rust_name(d)
        ty, _ = BACKINGS[backing(d)]
        method = {"i8": "i8", "i32": "i32", "i64": "i64"}[ty]
        out = [
            "/// `%s`: an enum backed by `%s`. Its value is kept as sent, so a peer's newer value is representable." % (d.fq, backing(d)),
            "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]",
            "pub struct %s(pub %s);" % (name, ty),
            "",
            "impl %s {" % name,
        ]
        for n, _, where in d.enumerators:
            out.append("    pub const %s: Self = Self(%d);" % (ident(n), self.m.value_of(d, n, where)))
        out += [
            "",
            "    pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {",
            "        Ok(Self(r.%s()?))" % method,
            "    }",
            "",
            "    pub fn write(self, w: &mut Writer) {",
            "        w.%s(self.0);" % method,
            "    }",
            "}",
        ]
        return out

    def emit_parcelable(self, d):
        name = rust_name(d)
        fields = [(field_ident(f.name), self.m.resolve(f.type, d), f) for f in d.fields]
        defaultable = self.m.defaultable(d)
        derive_default = defaultable and all(f.default is None and not (t.kind == "array" and t.fixed is not None and not t.nullable) for _, t, f in fields)
        derives = "Debug, Clone, PartialEq" + (", Default" if derive_default else "")
        out = ["/// `%s`: a parcelable." % d.fq, "#[derive(%s)]" % derives, "pub struct %s {" % name]
        for fname, t, f in fields:
            out.append("    pub %s: %s," % (fname, self.rty(t)))
        out.append("}")
        if defaultable and not derive_default:
            out += ["", "impl Default for %s {" % name, "    fn default() -> Self {", "        Self {"]
            for fname, t, f in fields:
                out.append("            %s: %s," % (fname, self.default_expr(t, f.default, d, f.where)))
            out += ["        }", "    }", "}"]
        body = self.consts_block(d)
        if body:
            body.append("")
        body += [
            "/// The parcelable's body (after its marker): its size, then its fields; fields an older",
            "/// writer did not send keep their defaults, and fields a newer writer added are skipped.",
            "pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {",
            "    let end = r.parcelable_body()?;",
        ]
        for i, (fname, t, f) in enumerate(fields):
            if f.default is not None or self.m.t_defaultable(t):
                missing = self.default_expr(t, f.default, d, f.where)
            else:
                missing = 'return Err(Malformed("%s.%s is missing"))' % (d.name, f.name)
            body.append("    let v%d = if r.within(end) { %s } else { %s };" % (i, self.rd(t), missing))
        body.append("    r.parcelable_end(end)?;")
        body.append("    Ok(Self { %s })" % ", ".join("%s: v%d" % (fname, i) for i, (fname, _, _) in enumerate(fields)))
        body += ["}", "", "/// The parcelable's body: its size, then its fields.", "pub fn write(&self, w: &mut Writer) {", "    let at = w.parcelable_body_start();"]
        for fname, t, f in fields:
            body += indent(self.wr(t, "self.%s" % fname, d))
        body += ["    w.parcelable_end(at);", "}"]
        body += self.value_helpers(d.name)
        out += ["", "impl %s {" % name] + indent(body) + ["}"]
        return out

    def emit_union(self, d):
        name = rust_name(d)
        if not d.fields:
            raise GenError("%s: a union without fields" % d.where)
        fields = [(variant_ident(f.name), self.m.resolve(f.type, d), f) for f in d.fields]
        out = ["/// `%s`: a union." % d.fq, "#[derive(Debug, Clone, PartialEq)]", "pub enum %s {" % name]
        for vname, t, f in fields:
            out.append("    %s(%s)," % (vname, self.rty(t)))
        out.append("}")
        if self.m.defaultable(d):
            vname, t, f = fields[0]
            out += ["", "impl Default for %s {" % name, "    fn default() -> Self {", "        Self::%s(%s)" % (vname, self.default_expr(t, f.default, d, f.where)), "    }", "}"]
        body = self.consts_block(d)
        if body:
            body.append("")
        body += ["/// The field's tag: its index in the declaration.", "pub fn tag(&self) -> i32 {", "    match self {"]
        for i, (vname, _, _) in enumerate(fields):
            body.append("        Self::%s(_) => %d," % (vname, i))
        body += ["    }", "}", ""]
        body += ["/// The union's body (after its marker): its tag, then that field.", "pub fn read(r: &mut Reader<'_>) -> Result<Self, Malformed> {", "    r.enter()?;", "    let v = match r.i32()? {"]
        for i, (vname, t, f) in enumerate(fields):
            body.append("        %d => Self::%s(%s)," % (i, vname, self.rd(t)))
        body += ['        _ => return Err(Malformed("an unknown %s tag")),' % d.name, "    };", "    r.leave();", "    Ok(v)", "}", ""]
        body += ["/// The union's body: its tag, then that field.", "pub fn write(&self, w: &mut Writer) {", "    match self {"]
        for i, (vname, t, f) in enumerate(fields):
            body += ["        Self::%s(v) => {" % vname, "            w.i32(%d);" % i] + indent(self.wr(t, "(*v)", d), 3) + ["        }"]
        body += ["    }", "}"]
        body += self.value_helpers(d.name)
        out += ["", "impl %s {" % name] + indent(body) + ["}"]
        return out

    def method_codes(self, d):
        explicit = [m.code is not None for m in d.methods]
        if any(explicit) and not all(explicit):
            raise GenError("%s: either every method of %s has a transaction id or none has" % (d.where, d.name))
        codes = [m.code if m.code is not None else i + 1 for i, m in enumerate(d.methods)]
        if len(set(codes)) != len(codes):
            raise GenError("%s: %s repeats a transaction id" % (d.where, d.name))
        return codes

    def emit_interface(self, d):
        iname = rust_name(d)
        mod = snake(iname)
        desc = d.fq
        if "Descriptor" in d.ann:
            m = re.search(r'value\s*=\s*("(?:\\.|[^"\\])*")', d.ann["Descriptor"])
            if not m:
                raise GenError("%s: cannot read @Descriptor" % d.where)
            desc = unescape(m.group(1)[1:-1])
        pkg = self.pkg
        codes = self.method_codes(d)
        server, proxy = iname + "Server", iname + "Proxy"
        methods = []
        for m, code in zip(d.methods, codes):
            ret = self.m.resolve(m.ret, d)
            params = []
            seen = set()
            for p in m.params:
                pt = self.m.resolve(p.type, d)
                if pt.kind == "void":
                    raise GenError("%s: a void parameter" % m.where)
                if p.direction != "in" and pt.is_copy() and pt.kind != "array":
                    raise GenError("%s: %s parameter %s of a primitive type" % (m.where, p.direction, p.name))
                pn = local_ident(p.name)
                if pn in seen:
                    raise GenError("%s: parameter %s twice" % (m.where, p.name))
                seen.add(pn)
                params.append((p, pt, pn))
            if m.oneway and (ret.kind != "void" or any(p.direction != "in" for p, _, _ in params)):
                raise GenError("%s: oneway %s returns something" % (m.where, m.name))
            outs = ([ret] if ret.kind != "void" else []) + [pt for p, pt, _ in params if p.direction != "in"]
            if not outs:
                ret_ty = "()"
            elif len(outs) == 1:
                ret_ty = self.rty(outs[0])
            else:
                ret_ty = "(%s)" % ", ".join(self.rty(t) for t in outs)
            methods.append((m, code, ret, params, outs, ret_ty, field_ident(m.name), "TRANSACTION_" + snake(m.name).upper()))
        names = [x[6] for x in methods]
        if len(set(names)) != len(names):
            raise GenError("%s: %s overloads a method name" % (d.where, d.name))

        out = ["/// `%s`: an interface (V%d)." % (d.fq, pkg.version), "pub mod %s {" % mod]
        b = ["use super::*;", ""]
        b += ['pub const DESCRIPTOR: &str = %s;' % rstr(desc), "/// The frozen version this module was generated from.", "pub const VERSION: i32 = %d;" % pkg.version,
              "/// That version's interface hash (`.hash`), which `getInterfaceHash` answers.", "pub const HASH: &str = %s;" % rstr(pkg.hash)]
        consts = self.consts_block(d)
        if consts:
            b += [""] + consts
        b.append("")
        for m, code, *_rest in methods:
            b.append("pub const %s: u32 = %d;" % (_rest[-1], code))
        # -- the server
        b += ["", "/// A server of `%s`. Each method answers one transaction; a method left out answers" % desc,
              "/// `EX_UNSUPPORTED_OPERATION`. `out` and `inout` values follow the return value in the tuple.",
              "pub trait %s: Send + Sync {" % server]
        for i, (m, code, ret, params, outs, ret_ty, fn, cname) in enumerate(methods):
            args = "".join(", %s: %s" % (pn, self.rty(pt)) for p, pt, pn in params if p.direction != "out")
            if i:
                b.append("")
            b.append("    /// `%s`%s (transaction %d)." % (m.name, " (oneway)" if m.oneway else "", code))
            b.append("    fn %s(&self, ctx: &Ctx<'_>%s) -> Result<%s, Status> {" % (fn, args, ret_ty))
            b.append('        Err(Status::unimplemented("%s.%s"))' % (d.name, m.name))
            b.append("    }")
        b.append("}")
        # -- the dispatcher
        b += ["", "/// Answer one transaction to a `%s` served by `svc`." % desc, "#[must_use]",
              "pub fn dispatch(svc: &dyn %s, call: HostCall) -> HostReply {" % server,
              "    if let Some(reply) = meta_reply(call.code, DESCRIPTOR) {",
              "        return reply;",
              "    }",
              "    if !is_user_code(call.code) {",
              "        return unknown_transaction();",
              "    }",
              "    let mut out = Writer::new();",
              "    match answer(svc, &call, &mut out) {",
              "        Ok(true) => out.into_reply(),",
              "        Ok(false) => unknown_transaction(),",
              "        Err(m) => illegal_argument(&m),",
              "    }",
              "}",
              "",
              "/// Serve `svc` on `broker`: the new host service's `ptr`, to answer as `Binder::Host` or to",
              "/// publish with `Broker::add_service_with_stability`.",
              "pub fn serve(broker: &Broker, svc: Arc<dyn %s>) -> u64 {" % server,
              "    broker.create_host_service_objects(move |call| dispatch(&*svc, call))",
              "}",
              "",
              "/// Decode, call, encode; `false` for a code the interface does not have.",
              "fn answer(svc: &dyn %s, call: &HostCall, w: &mut Writer) -> Result<bool, Malformed> {" % server,
              "    let ctx = Ctx { call };",
              "    let r = &mut Reader::with_objects(&call.data, &call.offsets, &call.fds);",
              "    r.interface_token(DESCRIPTOR)?;",
              "    match call.code {"]
        for m, code, ret, params, outs, ret_ty, fn, cname in methods:
            b.append("        %s => {" % cname)
            call_args = []
            for p, pt, pn in params:
                if p.direction == "out":
                    continue
                b.append("            let a_%s = %s;" % (pn.replace("r#", ""), self.rd(pt)))
                call_args.append("a_%s" % pn.replace("r#", ""))
            invoke = "svc.%s(&ctx%s)" % (fn, "".join(", " + a for a in call_args))
            if m.oneway:
                b.append("            // oneway: the caller does not wait, and hears nothing back.")
                b.append("            let _ = %s;" % invoke)
            else:
                b.append("            match %s {" % invoke)
                if not outs:
                    b.append("                Ok(()) => w.status_ok(),")
                else:
                    b.append("                Ok(ret) => {")
                    b.append("                    w.status_ok();")
                    for j, t in enumerate(outs):
                        place = "ret" if len(outs) == 1 else "ret.%d" % j
                        b += indent(self.wr(t, place, d), 5)
                    b.append("                }")
                b.append("                Err(s) => s.write(w),")
                b.append("            }")
            b.append("        }")
        b += ["        GET_INTERFACE_VERSION => {", "            w.status_ok();", "            w.i32(VERSION);", "        }",
              "        GET_INTERFACE_HASH => {", "            w.status_ok();", "            w.string16(HASH);", "        }",
              "        _ => return Ok(false),", "    }", "    Ok(true)", "}"]
        # -- the proxy
        b += ["", "/// A `%s` the host calls: a binder it holds a handle to (e.g. one a guest registered)." % desc,
              "pub struct %s {" % proxy, "    pub broker: Arc<Broker>,", "    pub handle: u32,", "}", "", "impl %s {" % proxy,
              "    #[must_use]", "    pub fn new(broker: Arc<Broker>, handle: u32) -> Self {", "        Self { broker, handle }", "    }"]
        for m, code, ret, params, outs, ret_ty, fn, cname in methods:
            sig = "".join(", %s: %s" % (pn, self.proxy_ty(pt)) for p, pt, pn in params if p.direction != "out")
            names_ = ", ".join(pn for p, pt, pn in params if p.direction != "out")
            b += ["", "    /// `%s`%s." % (m.name, " (oneway: returns once queued)" if m.oneway else ""),
                  "    pub fn %s(&self%s) -> Result<%s, CallError> {" % (fn, sig, "()" if m.oneway else ret_ty),
                  "        let w = encode_%s(%s);" % (fn.replace("r#", ""), names_),
                  "        let offsets = request_offsets(&w)?;"]
            if m.oneway:
                b.append("        self.broker.host_transact_oneway(self.handle, %s, w.data, &offsets).map_err(CallError::Transport)" % cname)
            else:
                b.append("        let reply = self.broker.host_transact(self.handle, %s, w.data, &offsets).map_err(CallError::Transport)?;" % cname)
                b.append("        decode_%s(&reply)" % fn.replace("r#", ""))
            b.append("    }")
        b += ["", "    /// `getInterfaceVersion`.", "    pub fn get_interface_version(&self) -> Result<i32, CallError> {",
              "        let mut w = Writer::new();", "        w.interface_token(DESCRIPTOR);",
              "        let reply = self.broker.host_transact(self.handle, GET_INTERFACE_VERSION, w.data, &[]).map_err(CallError::Transport)?;",
              "        let r = &mut Reader::new(&reply);", "        reply_status(r)?;", "        Ok(r.i32()?)", "    }",
              "", "    /// `getInterfaceHash`.", "    pub fn get_interface_hash(&self) -> Result<String, CallError> {",
              "        let mut w = Writer::new();", "        w.interface_token(DESCRIPTOR);",
              "        let reply = self.broker.host_transact(self.handle, GET_INTERFACE_HASH, w.data, &[]).map_err(CallError::Transport)?;",
              "        let r = &mut Reader::new(&reply);", "        reply_status(r)?;", '        Ok(r.string16()?.ok_or(Malformed("a null string"))?)', "    }", "}"]
        for m, code, ret, params, outs, ret_ty, fn, cname in methods:
            base = fn.replace("r#", "")
            sig = ", ".join("%s: %s" % (pn, self.proxy_ty(pt)) for p, pt, pn in params if p.direction != "out")
            b += ["", "/// `%s`'s request: the interface token, then the `in` and `inout` arguments." % m.name,
                  "#[must_use]", "pub fn encode_%s(%s) -> Writer {" % (base, sig),
                  "    let mut out = Writer::new();", "    let w = &mut out;", "    w.interface_token(DESCRIPTOR);"]
            for p, pt, pn in params:
                if p.direction == "out":
                    continue
                b += indent(self.wr(pt, pn if pt.is_copy() else "(*%s)" % pn, d))
            b += ["    out", "}"]
            if not m.oneway:
                b += ["", "/// `%s`'s reply: the status, then the return value and the `out` and `inout` values." % m.name,
                      "pub fn decode_%s(reply: &[u8]) -> Result<%s, CallError> {" % (base, ret_ty),
                      "    let r = &mut Reader::new(reply);", "    reply_status(r)?;"]
                for j, t in enumerate(outs):
                    b.append("    let v%d = %s;" % (j, self.rd(t)))
                if not outs:
                    b.append("    Ok(())")
                elif len(outs) == 1:
                    b.append("    Ok(v0)")
                else:
                    b.append("    Ok((%s))" % ", ".join("v%d" % j for j in range(len(outs))))
                b.append("}")
        out += indent(b) + ["}", "", "pub use %s::{%s, %s};" % (mod, proxy, server)]
        return out

    def proxy_ty(self, t):
        """A proxy's parameter: a Copy value by value, anything else by reference."""
        if t.is_copy():
            return self.rty(t)
        if t.kind == "array" and not t.nullable:
            if t.elem.kind == "prim" and t.elem.prim == "byte":
                return "&[u8]"
            return "&[%s]" % self.rty(t.elem)
        if t.kind == "string" and not t.nullable:
            return "&str"
        return "&%s" % self.rty(t)

    def emit_decl(self, d):
        if d.kind == "enum":
            return self.emit_enum(d)
        if d.kind == "parcelable":
            return self.emit_parcelable(d)
        if d.kind == "union":
            return self.emit_union(d)
        return self.emit_interface(d)

    def module(self):
        pkg = self.pkg
        lines = [
            HEADER.rstrip("\n"),
            "//! `%s` V%d, from the frozen AIDL API in `tools/aidl/%s/%d/` (interface hash `%s`)." % (pkg.name, pkg.version, pkg.name, pkg.version, pkg.hash),
            FILE_ALLOWS.rstrip("\n"),
            "",
            "use std::sync::Arc;",
            "",
            "use crate::binder::{Broker, HostCall, HostReply};",
            "use crate::hal::aidl::runtime::*;",
            "use crate::hal::parcel::{Malformed, Reader, Writer};",
        ]
        others = sorted({module_name(p.name) for p in self.m.packages if p.name != pkg.name})
        if others:
            lines.append("use crate::hal::aidl::{%s};" % ", ".join(others))
        for top in pkg.decls:
            for d in top.all():
                lines.append("")
                lines += self.emit_decl(d)
        return "\n".join(lines) + "\n"


def check_recursion(model):
    """A parcelable or union that holds itself by value (not through an array) has no size."""
    for d in model.decls.values():
        if d.kind not in ("parcelable", "union"):
            continue
        stack, seen = [d], set()
        while stack:
            x = stack.pop()
            for f in x.fields:
                t = model.resolve(f.type, x)
                if t.kind in ("parcelable", "union"):
                    if t.decl is d:
                        raise GenError("%s: %s holds itself by value, which needs a Box" % (f.where, d.fq))
                    if t.decl.fq not in seen:
                        seen.add(t.decl.fq)
                        stack.append(t.decl)


def check_supported(model):
    """Every type every declaration uses resolves; every problem, with where it is."""
    errors = []
    for d in model.decls.values():
        refs = [(f.type, f.where) for f in d.fields] + [(c.type, c.where) for c in d.consts]
        for m in d.methods:
            refs.append((m.ret, m.where))
            refs += [(p.type, m.where) for p in m.params]
        for tr, where in refs:
            try:
                model.resolve(tr, d)
            except GenError as e:
                errors.append(str(e))
    if errors:
        raise GenError("unsupported AIDL:\n  " + "\n  ".join(sorted(set(errors))))


def mod_rs(model):
    lines = [
        HEADER.rstrip("\n"),
        "//! AIDL interfaces served or called by the host, generated from the frozen API files under",
        "//! `tools/aidl` by `tools/gen_aidl.py`; what they share is `runtime.rs` (hand-written).",
        "",
        "mod runtime;",
        "",
        "pub use runtime::*;",
        "",
    ]
    for pkg in sorted(model.packages, key=lambda p: p.name):
        lines.append("pub mod %s;" % module_name(pkg.name))
    return "\n".join(lines) + "\n"


def generate(aidl_root=AIDL_ROOT, packages=PACKAGES, out_dir=None):
    """The generated files ({file name: text}); written to out_dir when it is given."""
    model = Model()
    for pkg, version in packages:
        model.load(aidl_root, pkg, version)
    check_supported(model)
    check_recursion(model)
    files = {"mod.rs": mod_rs(model)}
    for pkg in model.packages:
        files[module_name(pkg.name) + ".rs"] = Emitter(model, pkg).module()
    if out_dir is not None:
        os.makedirs(out_dir, exist_ok=True)
        for name, text in files.items():
            with open(os.path.join(out_dir, name), "w", encoding="utf-8", newline="\n") as f:
                f.write(text)
    return files, model


def stats(model):
    types = interfaces = methods = 0
    for d in model.decls.values():
        if d.kind == "interface":
            interfaces += 1
            methods += len(d.methods)
        else:
            types += 1
    return types, interfaces, methods


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="fail when the generated files are not up to date")
    args = ap.parse_args(argv)
    try:
        files, model = generate(out_dir=None if args.check else OUT_DIR)
    except GenError as e:
        print("gen_aidl: %s" % e, file=sys.stderr)
        return 1
    if args.check:
        stale = []
        for name, text in files.items():
            path = os.path.join(OUT_DIR, name)
            try:
                with open(path, encoding="utf-8", newline="") as f:
                    if f.read() != text:
                        stale.append(name)
            except FileNotFoundError:
                stale.append(name)
        if stale:
            print("gen_aidl: out of date: %s" % ", ".join(stale), file=sys.stderr)
            return 1
    types, interfaces, methods = stats(model)
    print("gen_aidl: %d packages, %d types, %d interfaces, %d methods" % (len(model.packages), types, interfaces, methods))
    return 0


if __name__ == "__main__":
    sys.exit(main())
